// Code generated by protoc-gen-go.
// source: rpc.proto
// DO NOT EDIT!

/*
Package lnrpc is a generated protocol buffer package.

It is generated from these files:
	rpc.proto

It has these top-level messages:
	Transaction
	GetTransactionsRequest
	TransactionDetails
	SendRequest
	SendResponse
	ChannelPoint
	LightningAddress
	SendManyRequest
	SendManyResponse
	SendCoinsRequest
	SendCoinsResponse
	NewAddressRequest
	NewWitnessAddressRequest
	NewAddressResponse
	ConnectPeerRequest
	ConnectPeerResponse
	HTLC
	ActiveChannel
	ListChannelsRequest
	ListChannelsResponse
	Peer
	ListPeersRequest
	ListPeersResponse
	GetInfoRequest
	GetInfoResponse
	ConfirmationUpdate
	ChannelOpenUpdate
	ChannelCloseUpdate
	CloseChannelRequest
	CloseStatusUpdate
	PendingUpdate
	OpenChannelRequest
	OpenStatusUpdate
	PendingChannelRequest
	PendingChannelResponse
	WalletBalanceRequest
	WalletBalanceResponse
	ChannelBalanceRequest
	ChannelBalanceResponse
	RoutingTableLink
	ShowRoutingTableRequest
	ShowRoutingTableResponse
	Invoice
	AddInvoiceResponse
	PaymentHash
	ListInvoiceRequest
	ListInvoiceResponse
	InvoiceSubscription
*/
package lnrpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis/google/api"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ChannelStatus int32

const (
	ChannelStatus_ALL     ChannelStatus = 0
	ChannelStatus_OPENING ChannelStatus = 1
	ChannelStatus_CLOSING ChannelStatus = 2
)

var ChannelStatus_name = map[int32]string{
	0: "ALL",
	1: "OPENING",
	2: "CLOSING",
}
var ChannelStatus_value = map[string]int32{
	"ALL":     0,
	"OPENING": 1,
	"CLOSING": 2,
}

func (x ChannelStatus) String() string {
	return proto.EnumName(ChannelStatus_name, int32(x))
}
func (ChannelStatus) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type NewAddressRequest_AddressType int32

const (
	NewAddressRequest_WITNESS_PUBKEY_HASH NewAddressRequest_AddressType = 0
	NewAddressRequest_NESTED_PUBKEY_HASH  NewAddressRequest_AddressType = 1
	NewAddressRequest_PUBKEY_HASH         NewAddressRequest_AddressType = 2
)

var NewAddressRequest_AddressType_name = map[int32]string{
	0: "WITNESS_PUBKEY_HASH",
	1: "NESTED_PUBKEY_HASH",
	2: "PUBKEY_HASH",
}
var NewAddressRequest_AddressType_value = map[string]int32{
	"WITNESS_PUBKEY_HASH": 0,
	"NESTED_PUBKEY_HASH":  1,
	"PUBKEY_HASH":         2,
}

func (x NewAddressRequest_AddressType) String() string {
	return proto.EnumName(NewAddressRequest_AddressType_name, int32(x))
}
func (NewAddressRequest_AddressType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{11, 0}
}

type Transaction struct {
	TxHash           string  `protobuf:"bytes,1,opt,name=tx_hash" json:"tx_hash,omitempty"`
	Amount           float64 `protobuf:"fixed64,2,opt,name=amount" json:"amount,omitempty"`
	NumConfirmations int32   `protobuf:"varint,3,opt,name=num_confirmations" json:"num_confirmations,omitempty"`
	BlockHash        string  `protobuf:"bytes,4,opt,name=block_hash" json:"block_hash,omitempty"`
	BlockHeight      int32   `protobuf:"varint,5,opt,name=block_height" json:"block_height,omitempty"`
	TimeStamp        int64   `protobuf:"varint,6,opt,name=time_stamp" json:"time_stamp,omitempty"`
	TotalFees        int64   `protobuf:"varint,7,opt,name=total_fees" json:"total_fees,omitempty"`
}

func (m *Transaction) Reset()                    { *m = Transaction{} }
func (m *Transaction) String() string            { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()               {}
func (*Transaction) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type GetTransactionsRequest struct {
}

func (m *GetTransactionsRequest) Reset()                    { *m = GetTransactionsRequest{} }
func (m *GetTransactionsRequest) String() string            { return proto.CompactTextString(m) }
func (*GetTransactionsRequest) ProtoMessage()               {}
func (*GetTransactionsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type TransactionDetails struct {
	Transactions []*Transaction `protobuf:"bytes,1,rep,name=transactions" json:"transactions,omitempty"`
}

func (m *TransactionDetails) Reset()                    { *m = TransactionDetails{} }
func (m *TransactionDetails) String() string            { return proto.CompactTextString(m) }
func (*TransactionDetails) ProtoMessage()               {}
func (*TransactionDetails) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *TransactionDetails) GetTransactions() []*Transaction {
	if m != nil {
		return m.Transactions
	}
	return nil
}

type SendRequest struct {
	Dest              []byte `protobuf:"bytes,1,opt,name=dest,proto3" json:"dest,omitempty"`
	DestString        string `protobuf:"bytes,2,opt,name=dest_string" json:"dest_string,omitempty"`
	Amt               int64  `protobuf:"varint,3,opt,name=amt" json:"amt,omitempty"`
	PaymentHash       []byte `protobuf:"bytes,4,opt,name=payment_hash,proto3" json:"payment_hash,omitempty"`
	PaymentHashString string `protobuf:"bytes,5,opt,name=payment_hash_string" json:"payment_hash_string,omitempty"`
	FastSend          bool   `protobuf:"varint,6,opt,name=fast_send" json:"fast_send,omitempty"`
}

func (m *SendRequest) Reset()                    { *m = SendRequest{} }
func (m *SendRequest) String() string            { return proto.CompactTextString(m) }
func (*SendRequest) ProtoMessage()               {}
func (*SendRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type SendResponse struct {
}

func (m *SendResponse) Reset()                    { *m = SendResponse{} }
func (m *SendResponse) String() string            { return proto.CompactTextString(m) }
func (*SendResponse) ProtoMessage()               {}
func (*SendResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type ChannelPoint struct {
	FundingTxid    []byte `protobuf:"bytes,1,opt,name=funding_txid,proto3" json:"funding_txid,omitempty"`
	FundingTxidStr string `protobuf:"bytes,2,opt,name=funding_txid_str" json:"funding_txid_str,omitempty"`
	OutputIndex    uint32 `protobuf:"varint,3,opt,name=output_index" json:"output_index,omitempty"`
}

func (m *ChannelPoint) Reset()                    { *m = ChannelPoint{} }
func (m *ChannelPoint) String() string            { return proto.CompactTextString(m) }
func (*ChannelPoint) ProtoMessage()               {}
func (*ChannelPoint) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type LightningAddress struct {
	Pubkey string `protobuf:"bytes,1,opt,name=pubkey" json:"pubkey,omitempty"`
	Host   string `protobuf:"bytes,2,opt,name=host" json:"host,omitempty"`
}

func (m *LightningAddress) Reset()                    { *m = LightningAddress{} }
func (m *LightningAddress) String() string            { return proto.CompactTextString(m) }
func (*LightningAddress) ProtoMessage()               {}
func (*LightningAddress) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type SendManyRequest struct {
	AddrToAmount map[string]int64 `protobuf:"bytes,1,rep,name=AddrToAmount" json:"AddrToAmount,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
}

func (m *SendManyRequest) Reset()                    { *m = SendManyRequest{} }
func (m *SendManyRequest) String() string            { return proto.CompactTextString(m) }
func (*SendManyRequest) ProtoMessage()               {}
func (*SendManyRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *SendManyRequest) GetAddrToAmount() map[string]int64 {
	if m != nil {
		return m.AddrToAmount
	}
	return nil
}

type SendManyResponse struct {
	Txid string `protobuf:"bytes,1,opt,name=txid" json:"txid,omitempty"`
}

func (m *SendManyResponse) Reset()                    { *m = SendManyResponse{} }
func (m *SendManyResponse) String() string            { return proto.CompactTextString(m) }
func (*SendManyResponse) ProtoMessage()               {}
func (*SendManyResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

type SendCoinsRequest struct {
	Addr   string `protobuf:"bytes,1,opt,name=addr" json:"addr,omitempty"`
	Amount int64  `protobuf:"varint,2,opt,name=amount" json:"amount,omitempty"`
}

func (m *SendCoinsRequest) Reset()                    { *m = SendCoinsRequest{} }
func (m *SendCoinsRequest) String() string            { return proto.CompactTextString(m) }
func (*SendCoinsRequest) ProtoMessage()               {}
func (*SendCoinsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

type SendCoinsResponse struct {
	Txid string `protobuf:"bytes,1,opt,name=txid" json:"txid,omitempty"`
}

func (m *SendCoinsResponse) Reset()                    { *m = SendCoinsResponse{} }
func (m *SendCoinsResponse) String() string            { return proto.CompactTextString(m) }
func (*SendCoinsResponse) ProtoMessage()               {}
func (*SendCoinsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

type NewAddressRequest struct {
	Type NewAddressRequest_AddressType `protobuf:"varint,1,opt,name=type,enum=lnrpc.NewAddressRequest_AddressType" json:"type,omitempty"`
}

func (m *NewAddressRequest) Reset()                    { *m = NewAddressRequest{} }
func (m *NewAddressRequest) String() string            { return proto.CompactTextString(m) }
func (*NewAddressRequest) ProtoMessage()               {}
func (*NewAddressRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

type NewWitnessAddressRequest struct {
}

func (m *NewWitnessAddressRequest) Reset()                    { *m = NewWitnessAddressRequest{} }
func (m *NewWitnessAddressRequest) String() string            { return proto.CompactTextString(m) }
func (*NewWitnessAddressRequest) ProtoMessage()               {}
func (*NewWitnessAddressRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

type NewAddressResponse struct {
	Address string `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
}

func (m *NewAddressResponse) Reset()                    { *m = NewAddressResponse{} }
func (m *NewAddressResponse) String() string            { return proto.CompactTextString(m) }
func (*NewAddressResponse) ProtoMessage()               {}
func (*NewAddressResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

type ConnectPeerRequest struct {
	Addr *LightningAddress `protobuf:"bytes,1,opt,name=addr" json:"addr,omitempty"`
}

func (m *ConnectPeerRequest) Reset()                    { *m = ConnectPeerRequest{} }
func (m *ConnectPeerRequest) String() string            { return proto.CompactTextString(m) }
func (*ConnectPeerRequest) ProtoMessage()               {}
func (*ConnectPeerRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *ConnectPeerRequest) GetAddr() *LightningAddress {
	if m != nil {
		return m.Addr
	}
	return nil
}

type ConnectPeerResponse struct {
	PeerId int32 `protobuf:"varint,1,opt,name=peer_id" json:"peer_id,omitempty"`
}

func (m *ConnectPeerResponse) Reset()                    { *m = ConnectPeerResponse{} }
func (m *ConnectPeerResponse) String() string            { return proto.CompactTextString(m) }
func (*ConnectPeerResponse) ProtoMessage()               {}
func (*ConnectPeerResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

type HTLC struct {
	Incoming         bool   `protobuf:"varint,1,opt,name=incoming" json:"incoming,omitempty"`
	Amount           int64  `protobuf:"varint,2,opt,name=amount" json:"amount,omitempty"`
	HashLock         []byte `protobuf:"bytes,3,opt,name=hash_lock,proto3" json:"hash_lock,omitempty"`
	ExpirationHeight uint32 `protobuf:"varint,4,opt,name=expiration_height" json:"expiration_height,omitempty"`
	RevocationDelay  uint32 `protobuf:"varint,5,opt,name=revocation_delay" json:"revocation_delay,omitempty"`
}

func (m *HTLC) Reset()                    { *m = HTLC{} }
func (m *HTLC) String() string            { return proto.CompactTextString(m) }
func (*HTLC) ProtoMessage()               {}
func (*HTLC) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

type ActiveChannel struct {
	RemotePubkey          string  `protobuf:"bytes,1,opt,name=remote_pubkey" json:"remote_pubkey,omitempty"`
	ChannelPoint          string  `protobuf:"bytes,2,opt,name=channel_point" json:"channel_point,omitempty"`
	Capacity              int64   `protobuf:"varint,3,opt,name=capacity" json:"capacity,omitempty"`
	LocalBalance          int64   `protobuf:"varint,4,opt,name=local_balance" json:"local_balance,omitempty"`
	RemoteBalance         int64   `protobuf:"varint,5,opt,name=remote_balance" json:"remote_balance,omitempty"`
	UnsettledBalance      int64   `protobuf:"varint,6,opt,name=unsettled_balance" json:"unsettled_balance,omitempty"`
	TotalSatoshisSent     int64   `protobuf:"varint,7,opt,name=total_satoshis_sent" json:"total_satoshis_sent,omitempty"`
	TotalSatoshisReceived int64   `protobuf:"varint,8,opt,name=total_satoshis_received" json:"total_satoshis_received,omitempty"`
	NumUpdates            uint64  `protobuf:"varint,9,opt,name=num_updates" json:"num_updates,omitempty"`
	PendingHtlcs          []*HTLC `protobuf:"bytes,10,rep,name=pending_htlcs" json:"pending_htlcs,omitempty"`
}

func (m *ActiveChannel) Reset()                    { *m = ActiveChannel{} }
func (m *ActiveChannel) String() string            { return proto.CompactTextString(m) }
func (*ActiveChannel) ProtoMessage()               {}
func (*ActiveChannel) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *ActiveChannel) GetPendingHtlcs() []*HTLC {
	if m != nil {
		return m.PendingHtlcs
	}
	return nil
}

type ListChannelsRequest struct {
}

func (m *ListChannelsRequest) Reset()                    { *m = ListChannelsRequest{} }
func (m *ListChannelsRequest) String() string            { return proto.CompactTextString(m) }
func (*ListChannelsRequest) ProtoMessage()               {}
func (*ListChannelsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

type ListChannelsResponse struct {
	Channels []*ActiveChannel `protobuf:"bytes,11,rep,name=channels" json:"channels,omitempty"`
}

func (m *ListChannelsResponse) Reset()                    { *m = ListChannelsResponse{} }
func (m *ListChannelsResponse) String() string            { return proto.CompactTextString(m) }
func (*ListChannelsResponse) ProtoMessage()               {}
func (*ListChannelsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *ListChannelsResponse) GetChannels() []*ActiveChannel {
	if m != nil {
		return m.Channels
	}
	return nil
}

type Peer struct {
	PubKey    string `protobuf:"bytes,1,opt,name=pub_key" json:"pub_key,omitempty"`
	PeerId    int32  `protobuf:"varint,2,opt,name=peer_id" json:"peer_id,omitempty"`
	Address   string `protobuf:"bytes,3,opt,name=address" json:"address,omitempty"`
	BytesSent uint64 `protobuf:"varint,4,opt,name=bytes_sent" json:"bytes_sent,omitempty"`
	BytesRecv uint64 `protobuf:"varint,5,opt,name=bytes_recv" json:"bytes_recv,omitempty"`
	SatSent   int64  `protobuf:"varint,6,opt,name=sat_sent" json:"sat_sent,omitempty"`
	SatRecv   int64  `protobuf:"varint,7,opt,name=sat_recv" json:"sat_recv,omitempty"`
	Inbound   bool   `protobuf:"varint,8,opt,name=inbound" json:"inbound,omitempty"`
}

func (m *Peer) Reset()                    { *m = Peer{} }
func (m *Peer) String() string            { return proto.CompactTextString(m) }
func (*Peer) ProtoMessage()               {}
func (*Peer) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

type ListPeersRequest struct {
}

func (m *ListPeersRequest) Reset()                    { *m = ListPeersRequest{} }
func (m *ListPeersRequest) String() string            { return proto.CompactTextString(m) }
func (*ListPeersRequest) ProtoMessage()               {}
func (*ListPeersRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

type ListPeersResponse struct {
	Peers []*Peer `protobuf:"bytes,1,rep,name=peers" json:"peers,omitempty"`
}

func (m *ListPeersResponse) Reset()                    { *m = ListPeersResponse{} }
func (m *ListPeersResponse) String() string            { return proto.CompactTextString(m) }
func (*ListPeersResponse) ProtoMessage()               {}
func (*ListPeersResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

func (m *ListPeersResponse) GetPeers() []*Peer {
	if m != nil {
		return m.Peers
	}
	return nil
}

type GetInfoRequest struct {
}

func (m *GetInfoRequest) Reset()                    { *m = GetInfoRequest{} }
func (m *GetInfoRequest) String() string            { return proto.CompactTextString(m) }
func (*GetInfoRequest) ProtoMessage()               {}
func (*GetInfoRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{23} }

type GetInfoResponse struct {
	LightningId        string `protobuf:"bytes,1,opt,name=lightning_id" json:"lightning_id,omitempty"`
	IdentityPubkey     string `protobuf:"bytes,3,opt,name=identity_pubkey" json:"identity_pubkey,omitempty"`
	NumPendingChannels uint32 `protobuf:"varint,4,opt,name=num_pending_channels" json:"num_pending_channels,omitempty"`
	NumActiveChannels  uint32 `protobuf:"varint,5,opt,name=num_active_channels" json:"num_active_channels,omitempty"`
	NumPeers           uint32 `protobuf:"varint,6,opt,name=num_peers" json:"num_peers,omitempty"`
	BlockHeight        uint32 `protobuf:"varint,7,opt,name=block_height" json:"block_height,omitempty"`
	SyncedToChain      bool   `protobuf:"varint,8,opt,name=synced_to_chain" json:"synced_to_chain,omitempty"`
}

func (m *GetInfoResponse) Reset()                    { *m = GetInfoResponse{} }
func (m *GetInfoResponse) String() string            { return proto.CompactTextString(m) }
func (*GetInfoResponse) ProtoMessage()               {}
func (*GetInfoResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{24} }

type ConfirmationUpdate struct {
	BlockSha     []byte `protobuf:"bytes,1,opt,name=block_sha,proto3" json:"block_sha,omitempty"`
	BlockHeight  int32  `protobuf:"varint,2,opt,name=block_height" json:"block_height,omitempty"`
	NumConfsLeft uint32 `protobuf:"varint,3,opt,name=num_confs_left" json:"num_confs_left,omitempty"`
}

func (m *ConfirmationUpdate) Reset()                    { *m = ConfirmationUpdate{} }
func (m *ConfirmationUpdate) String() string            { return proto.CompactTextString(m) }
func (*ConfirmationUpdate) ProtoMessage()               {}
func (*ConfirmationUpdate) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{25} }

type ChannelOpenUpdate struct {
	ChannelPoint *ChannelPoint `protobuf:"bytes,1,opt,name=channel_point" json:"channel_point,omitempty"`
}

func (m *ChannelOpenUpdate) Reset()                    { *m = ChannelOpenUpdate{} }
func (m *ChannelOpenUpdate) String() string            { return proto.CompactTextString(m) }
func (*ChannelOpenUpdate) ProtoMessage()               {}
func (*ChannelOpenUpdate) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{26} }

func (m *ChannelOpenUpdate) GetChannelPoint() *ChannelPoint {
	if m != nil {
		return m.ChannelPoint
	}
	return nil
}

type ChannelCloseUpdate struct {
	ClosingTxid []byte `protobuf:"bytes,1,opt,name=closing_txid,proto3" json:"closing_txid,omitempty"`
	Success     bool   `protobuf:"varint,2,opt,name=success" json:"success,omitempty"`
}

func (m *ChannelCloseUpdate) Reset()                    { *m = ChannelCloseUpdate{} }
func (m *ChannelCloseUpdate) String() string            { return proto.CompactTextString(m) }
func (*ChannelCloseUpdate) ProtoMessage()               {}
func (*ChannelCloseUpdate) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{27} }

type CloseChannelRequest struct {
	ChannelPoint *ChannelPoint `protobuf:"bytes,1,opt,name=channel_point" json:"channel_point,omitempty"`
	TimeLimit    int64         `protobuf:"varint,2,opt,name=time_limit" json:"time_limit,omitempty"`
	Force        bool          `protobuf:"varint,3,opt,name=force" json:"force,omitempty"`
}

func (m *CloseChannelRequest) Reset()                    { *m = CloseChannelRequest{} }
func (m *CloseChannelRequest) String() string            { return proto.CompactTextString(m) }
func (*CloseChannelRequest) ProtoMessage()               {}
func (*CloseChannelRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{28} }

func (m *CloseChannelRequest) GetChannelPoint() *ChannelPoint {
	if m != nil {
		return m.ChannelPoint
	}
	return nil
}

type CloseStatusUpdate struct {
	// Types that are valid to be assigned to Update:
	//	*CloseStatusUpdate_ClosePending
	//	*CloseStatusUpdate_Confirmation
	//	*CloseStatusUpdate_ChanClose
	Update isCloseStatusUpdate_Update `protobuf_oneof:"update"`
}

func (m *CloseStatusUpdate) Reset()                    { *m = CloseStatusUpdate{} }
func (m *CloseStatusUpdate) String() string            { return proto.CompactTextString(m) }
func (*CloseStatusUpdate) ProtoMessage()               {}
func (*CloseStatusUpdate) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{29} }

type isCloseStatusUpdate_Update interface {
	isCloseStatusUpdate_Update()
}

type CloseStatusUpdate_ClosePending struct {
	ClosePending *PendingUpdate `protobuf:"bytes,1,opt,name=close_pending,oneof"`
}
type CloseStatusUpdate_Confirmation struct {
	Confirmation *ConfirmationUpdate `protobuf:"bytes,2,opt,name=confirmation,oneof"`
}
type CloseStatusUpdate_ChanClose struct {
	ChanClose *ChannelCloseUpdate `protobuf:"bytes,3,opt,name=chan_close,oneof"`
}

func (*CloseStatusUpdate_ClosePending) isCloseStatusUpdate_Update() {}
func (*CloseStatusUpdate_Confirmation) isCloseStatusUpdate_Update() {}
func (*CloseStatusUpdate_ChanClose) isCloseStatusUpdate_Update()    {}

func (m *CloseStatusUpdate) GetUpdate() isCloseStatusUpdate_Update {
	if m != nil {
		return m.Update
	}
	return nil
}

func (m *CloseStatusUpdate) GetClosePending() *PendingUpdate {
	if x, ok := m.GetUpdate().(*CloseStatusUpdate_ClosePending); ok {
		return x.ClosePending
	}
	return nil
}

func (m *CloseStatusUpdate) GetConfirmation() *ConfirmationUpdate {
	if x, ok := m.GetUpdate().(*CloseStatusUpdate_Confirmation); ok {
		return x.Confirmation
	}
	return nil
}

func (m *CloseStatusUpdate) GetChanClose() *ChannelCloseUpdate {
	if x, ok := m.GetUpdate().(*CloseStatusUpdate_ChanClose); ok {
		return x.ChanClose
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*CloseStatusUpdate) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _CloseStatusUpdate_OneofMarshaler, _CloseStatusUpdate_OneofUnmarshaler, _CloseStatusUpdate_OneofSizer, []interface{}{
		(*CloseStatusUpdate_ClosePending)(nil),
		(*CloseStatusUpdate_Confirmation)(nil),
		(*CloseStatusUpdate_ChanClose)(nil),
	}
}

func _CloseStatusUpdate_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*CloseStatusUpdate)
	// update
	switch x := m.Update.(type) {
	case *CloseStatusUpdate_ClosePending:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ClosePending); err != nil {
			return err
		}
	case *CloseStatusUpdate_Confirmation:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Confirmation); err != nil {
			return err
		}
	case *CloseStatusUpdate_ChanClose:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ChanClose); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("CloseStatusUpdate.Update has unexpected type %T", x)
	}
	return nil
}

func _CloseStatusUpdate_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*CloseStatusUpdate)
	switch tag {
	case 1: // update.close_pending
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(PendingUpdate)
		err := b.DecodeMessage(msg)
		m.Update = &CloseStatusUpdate_ClosePending{msg}
		return true, err
	case 2: // update.confirmation
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ConfirmationUpdate)
		err := b.DecodeMessage(msg)
		m.Update = &CloseStatusUpdate_Confirmation{msg}
		return true, err
	case 3: // update.chan_close
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ChannelCloseUpdate)
		err := b.DecodeMessage(msg)
		m.Update = &CloseStatusUpdate_ChanClose{msg}
		return true, err
	default:
		return false, nil
	}
}

func _CloseStatusUpdate_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*CloseStatusUpdate)
	// update
	switch x := m.Update.(type) {
	case *CloseStatusUpdate_ClosePending:
		s := proto.Size(x.ClosePending)
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *CloseStatusUpdate_Confirmation:
		s := proto.Size(x.Confirmation)
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *CloseStatusUpdate_ChanClose:
		s := proto.Size(x.ChanClose)
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type PendingUpdate struct {
	Txid []byte `protobuf:"bytes,1,opt,name=txid,proto3" json:"txid,omitempty"`
}

func (m *PendingUpdate) Reset()                    { *m = PendingUpdate{} }
func (m *PendingUpdate) String() string            { return proto.CompactTextString(m) }
func (*PendingUpdate) ProtoMessage()               {}
func (*PendingUpdate) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{30} }

type OpenChannelRequest struct {
	TargetPeerId        int32  `protobuf:"varint,1,opt,name=target_peer_id" json:"target_peer_id,omitempty"`
	NodePubkey          []byte `protobuf:"bytes,2,opt,name=node_pubkey,proto3" json:"node_pubkey,omitempty"`
	NodePubkeyString    string `protobuf:"bytes,3,opt,name=node_pubkey_string" json:"node_pubkey_string,omitempty"`
	LocalFundingAmount  int64  `protobuf:"varint,4,opt,name=local_funding_amount" json:"local_funding_amount,omitempty"`
	RemoteFundingAmount int64  `protobuf:"varint,5,opt,name=remote_funding_amount" json:"remote_funding_amount,omitempty"`
	CommissionSize      int64  `protobuf:"varint,6,opt,name=commission_size" json:"commission_size,omitempty"`
	NumConfs            uint32 `protobuf:"varint,7,opt,name=num_confs" json:"num_confs,omitempty"`
}

func (m *OpenChannelRequest) Reset()                    { *m = OpenChannelRequest{} }
func (m *OpenChannelRequest) String() string            { return proto.CompactTextString(m) }
func (*OpenChannelRequest) ProtoMessage()               {}
func (*OpenChannelRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{31} }

type OpenStatusUpdate struct {
	// Types that are valid to be assigned to Update:
	//	*OpenStatusUpdate_ChanPending
	//	*OpenStatusUpdate_Confirmation
	//	*OpenStatusUpdate_ChanOpen
	Update isOpenStatusUpdate_Update `protobuf_oneof:"update"`
}

func (m *OpenStatusUpdate) Reset()                    { *m = OpenStatusUpdate{} }
func (m *OpenStatusUpdate) String() string            { return proto.CompactTextString(m) }
func (*OpenStatusUpdate) ProtoMessage()               {}
func (*OpenStatusUpdate) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{32} }

type isOpenStatusUpdate_Update interface {
	isOpenStatusUpdate_Update()
}

type OpenStatusUpdate_ChanPending struct {
	ChanPending *PendingUpdate `protobuf:"bytes,1,opt,name=chan_pending,oneof"`
}
type OpenStatusUpdate_Confirmation struct {
	Confirmation *ConfirmationUpdate `protobuf:"bytes,2,opt,name=confirmation,oneof"`
}
type OpenStatusUpdate_ChanOpen struct {
	ChanOpen *ChannelOpenUpdate `protobuf:"bytes,3,opt,name=chan_open,oneof"`
}

func (*OpenStatusUpdate_ChanPending) isOpenStatusUpdate_Update()  {}
func (*OpenStatusUpdate_Confirmation) isOpenStatusUpdate_Update() {}
func (*OpenStatusUpdate_ChanOpen) isOpenStatusUpdate_Update()     {}

func (m *OpenStatusUpdate) GetUpdate() isOpenStatusUpdate_Update {
	if m != nil {
		return m.Update
	}
	return nil
}

func (m *OpenStatusUpdate) GetChanPending() *PendingUpdate {
	if x, ok := m.GetUpdate().(*OpenStatusUpdate_ChanPending); ok {
		return x.ChanPending
	}
	return nil
}

func (m *OpenStatusUpdate) GetConfirmation() *ConfirmationUpdate {
	if x, ok := m.GetUpdate().(*OpenStatusUpdate_Confirmation); ok {
		return x.Confirmation
	}
	return nil
}

func (m *OpenStatusUpdate) GetChanOpen() *ChannelOpenUpdate {
	if x, ok := m.GetUpdate().(*OpenStatusUpdate_ChanOpen); ok {
		return x.ChanOpen
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*OpenStatusUpdate) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _OpenStatusUpdate_OneofMarshaler, _OpenStatusUpdate_OneofUnmarshaler, _OpenStatusUpdate_OneofSizer, []interface{}{
		(*OpenStatusUpdate_ChanPending)(nil),
		(*OpenStatusUpdate_Confirmation)(nil),
		(*OpenStatusUpdate_ChanOpen)(nil),
	}
}

func _OpenStatusUpdate_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*OpenStatusUpdate)
	// update
	switch x := m.Update.(type) {
	case *OpenStatusUpdate_ChanPending:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ChanPending); err != nil {
			return err
		}
	case *OpenStatusUpdate_Confirmation:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Confirmation); err != nil {
			return err
		}
	case *OpenStatusUpdate_ChanOpen:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ChanOpen); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("OpenStatusUpdate.Update has unexpected type %T", x)
	}
	return nil
}

func _OpenStatusUpdate_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*OpenStatusUpdate)
	switch tag {
	case 1: // update.chan_pending
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(PendingUpdate)
		err := b.DecodeMessage(msg)
		m.Update = &OpenStatusUpdate_ChanPending{msg}
		return true, err
	case 2: // update.confirmation
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ConfirmationUpdate)
		err := b.DecodeMessage(msg)
		m.Update = &OpenStatusUpdate_Confirmation{msg}
		return true, err
	case 3: // update.chan_open
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ChannelOpenUpdate)
		err := b.DecodeMessage(msg)
		m.Update = &OpenStatusUpdate_ChanOpen{msg}
		return true, err
	default:
		return false, nil
	}
}

func _OpenStatusUpdate_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*OpenStatusUpdate)
	// update
	switch x := m.Update.(type) {
	case *OpenStatusUpdate_ChanPending:
		s := proto.Size(x.ChanPending)
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *OpenStatusUpdate_Confirmation:
		s := proto.Size(x.Confirmation)
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *OpenStatusUpdate_ChanOpen:
		s := proto.Size(x.ChanOpen)
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type PendingChannelRequest struct {
	Status ChannelStatus `protobuf:"varint,1,opt,name=status,enum=lnrpc.ChannelStatus" json:"status,omitempty"`
}

func (m *PendingChannelRequest) Reset()                    { *m = PendingChannelRequest{} }
func (m *PendingChannelRequest) String() string            { return proto.CompactTextString(m) }
func (*PendingChannelRequest) ProtoMessage()               {}
func (*PendingChannelRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{33} }

type PendingChannelResponse struct {
	PendingChannels []*PendingChannelResponse_PendingChannel `protobuf:"bytes,1,rep,name=pending_channels" json:"pending_channels,omitempty"`
}

func (m *PendingChannelResponse) Reset()                    { *m = PendingChannelResponse{} }
func (m *PendingChannelResponse) String() string            { return proto.CompactTextString(m) }
func (*PendingChannelResponse) ProtoMessage()               {}
func (*PendingChannelResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{34} }

func (m *PendingChannelResponse) GetPendingChannels() []*PendingChannelResponse_PendingChannel {
	if m != nil {
		return m.PendingChannels
	}
	return nil
}

type PendingChannelResponse_PendingChannel struct {
	PeerId        int32         `protobuf:"varint,1,opt,name=peer_id" json:"peer_id,omitempty"`
	IdentityKey   string        `protobuf:"bytes,2,opt,name=identity_key" json:"identity_key,omitempty"`
	ChannelPoint  string        `protobuf:"bytes,3,opt,name=channel_point" json:"channel_point,omitempty"`
	Capacity      int64         `protobuf:"varint,4,opt,name=capacity" json:"capacity,omitempty"`
	LocalBalance  int64         `protobuf:"varint,5,opt,name=local_balance" json:"local_balance,omitempty"`
	RemoteBalance int64         `protobuf:"varint,6,opt,name=remote_balance" json:"remote_balance,omitempty"`
	ClosingTxid   string        `protobuf:"bytes,7,opt,name=closing_txid" json:"closing_txid,omitempty"`
	Status        ChannelStatus `protobuf:"varint,8,opt,name=status,enum=lnrpc.ChannelStatus" json:"status,omitempty"`
}

func (m *PendingChannelResponse_PendingChannel) Reset()         { *m = PendingChannelResponse_PendingChannel{} }
func (m *PendingChannelResponse_PendingChannel) String() string { return proto.CompactTextString(m) }
func (*PendingChannelResponse_PendingChannel) ProtoMessage()    {}
func (*PendingChannelResponse_PendingChannel) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{34, 0}
}

type WalletBalanceRequest struct {
	WitnessOnly bool `protobuf:"varint,1,opt,name=witness_only" json:"witness_only,omitempty"`
}

func (m *WalletBalanceRequest) Reset()                    { *m = WalletBalanceRequest{} }
func (m *WalletBalanceRequest) String() string            { return proto.CompactTextString(m) }
func (*WalletBalanceRequest) ProtoMessage()               {}
func (*WalletBalanceRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{35} }

type WalletBalanceResponse struct {
	Balance float64 `protobuf:"fixed64,1,opt,name=balance" json:"balance,omitempty"`
}

func (m *WalletBalanceResponse) Reset()                    { *m = WalletBalanceResponse{} }
func (m *WalletBalanceResponse) String() string            { return proto.CompactTextString(m) }
func (*WalletBalanceResponse) ProtoMessage()               {}
func (*WalletBalanceResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{36} }

type ChannelBalanceRequest struct {
}

func (m *ChannelBalanceRequest) Reset()                    { *m = ChannelBalanceRequest{} }
func (m *ChannelBalanceRequest) String() string            { return proto.CompactTextString(m) }
func (*ChannelBalanceRequest) ProtoMessage()               {}
func (*ChannelBalanceRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{37} }

type ChannelBalanceResponse struct {
	Balance int64 `protobuf:"varint,1,opt,name=balance" json:"balance,omitempty"`
}

func (m *ChannelBalanceResponse) Reset()                    { *m = ChannelBalanceResponse{} }
func (m *ChannelBalanceResponse) String() string            { return proto.CompactTextString(m) }
func (*ChannelBalanceResponse) ProtoMessage()               {}
func (*ChannelBalanceResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{38} }

type RoutingTableLink struct {
	Id1      string  `protobuf:"bytes,1,opt,name=id1" json:"id1,omitempty"`
	Id2      string  `protobuf:"bytes,2,opt,name=id2" json:"id2,omitempty"`
	Outpoint string  `protobuf:"bytes,3,opt,name=outpoint" json:"outpoint,omitempty"`
	Capacity int64   `protobuf:"varint,4,opt,name=capacity" json:"capacity,omitempty"`
	Weight   float64 `protobuf:"fixed64,5,opt,name=weight" json:"weight,omitempty"`
}

func (m *RoutingTableLink) Reset()                    { *m = RoutingTableLink{} }
func (m *RoutingTableLink) String() string            { return proto.CompactTextString(m) }
func (*RoutingTableLink) ProtoMessage()               {}
func (*RoutingTableLink) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{39} }

type ShowRoutingTableRequest struct {
}

func (m *ShowRoutingTableRequest) Reset()                    { *m = ShowRoutingTableRequest{} }
func (m *ShowRoutingTableRequest) String() string            { return proto.CompactTextString(m) }
func (*ShowRoutingTableRequest) ProtoMessage()               {}
func (*ShowRoutingTableRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{40} }

type ShowRoutingTableResponse struct {
	Channels []*RoutingTableLink `protobuf:"bytes,1,rep,name=channels" json:"channels,omitempty"`
}

func (m *ShowRoutingTableResponse) Reset()                    { *m = ShowRoutingTableResponse{} }
func (m *ShowRoutingTableResponse) String() string            { return proto.CompactTextString(m) }
func (*ShowRoutingTableResponse) ProtoMessage()               {}
func (*ShowRoutingTableResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{41} }

func (m *ShowRoutingTableResponse) GetChannels() []*RoutingTableLink {
	if m != nil {
		return m.Channels
	}
	return nil
}

type Invoice struct {
	Memo         string `protobuf:"bytes,1,opt,name=memo" json:"memo,omitempty"`
	Receipt      []byte `protobuf:"bytes,2,opt,name=receipt,proto3" json:"receipt,omitempty"`
	RPreimage    []byte `protobuf:"bytes,3,opt,name=r_preimage,proto3" json:"r_preimage,omitempty"`
	RHash        []byte `protobuf:"bytes,4,opt,name=r_hash,proto3" json:"r_hash,omitempty"`
	Value        int64  `protobuf:"varint,5,opt,name=value" json:"value,omitempty"`
	Settled      bool   `protobuf:"varint,6,opt,name=settled" json:"settled,omitempty"`
	CreationDate int64  `protobuf:"varint,7,opt,name=creation_date" json:"creation_date,omitempty"`
	SettleDate   int64  `protobuf:"varint,8,opt,name=settle_date" json:"settle_date,omitempty"`
}

func (m *Invoice) Reset()                    { *m = Invoice{} }
func (m *Invoice) String() string            { return proto.CompactTextString(m) }
func (*Invoice) ProtoMessage()               {}
func (*Invoice) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{42} }

type AddInvoiceResponse struct {
	RHash []byte `protobuf:"bytes,1,opt,name=r_hash,proto3" json:"r_hash,omitempty"`
}

func (m *AddInvoiceResponse) Reset()                    { *m = AddInvoiceResponse{} }
func (m *AddInvoiceResponse) String() string            { return proto.CompactTextString(m) }
func (*AddInvoiceResponse) ProtoMessage()               {}
func (*AddInvoiceResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{43} }

type PaymentHash struct {
	RHashStr string `protobuf:"bytes,1,opt,name=r_hash_str" json:"r_hash_str,omitempty"`
	RHash    []byte `protobuf:"bytes,2,opt,name=r_hash,proto3" json:"r_hash,omitempty"`
}

func (m *PaymentHash) Reset()                    { *m = PaymentHash{} }
func (m *PaymentHash) String() string            { return proto.CompactTextString(m) }
func (*PaymentHash) ProtoMessage()               {}
func (*PaymentHash) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{44} }

type ListInvoiceRequest struct {
	PendingOnly bool `protobuf:"varint,1,opt,name=pending_only" json:"pending_only,omitempty"`
}

func (m *ListInvoiceRequest) Reset()                    { *m = ListInvoiceRequest{} }
func (m *ListInvoiceRequest) String() string            { return proto.CompactTextString(m) }
func (*ListInvoiceRequest) ProtoMessage()               {}
func (*ListInvoiceRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{45} }

type ListInvoiceResponse struct {
	Invoices []*Invoice `protobuf:"bytes,1,rep,name=invoices" json:"invoices,omitempty"`
}

func (m *ListInvoiceResponse) Reset()                    { *m = ListInvoiceResponse{} }
func (m *ListInvoiceResponse) String() string            { return proto.CompactTextString(m) }
func (*ListInvoiceResponse) ProtoMessage()               {}
func (*ListInvoiceResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{46} }

func (m *ListInvoiceResponse) GetInvoices() []*Invoice {
	if m != nil {
		return m.Invoices
	}
	return nil
}

type InvoiceSubscription struct {
}

func (m *InvoiceSubscription) Reset()                    { *m = InvoiceSubscription{} }
func (m *InvoiceSubscription) String() string            { return proto.CompactTextString(m) }
func (*InvoiceSubscription) ProtoMessage()               {}
func (*InvoiceSubscription) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{47} }

func init() {
	proto.RegisterType((*Transaction)(nil), "lnrpc.Transaction")
	proto.RegisterType((*GetTransactionsRequest)(nil), "lnrpc.GetTransactionsRequest")
	proto.RegisterType((*TransactionDetails)(nil), "lnrpc.TransactionDetails")
	proto.RegisterType((*SendRequest)(nil), "lnrpc.SendRequest")
	proto.RegisterType((*SendResponse)(nil), "lnrpc.SendResponse")
	proto.RegisterType((*ChannelPoint)(nil), "lnrpc.ChannelPoint")
	proto.RegisterType((*LightningAddress)(nil), "lnrpc.LightningAddress")
	proto.RegisterType((*SendManyRequest)(nil), "lnrpc.SendManyRequest")
	proto.RegisterType((*SendManyResponse)(nil), "lnrpc.SendManyResponse")
	proto.RegisterType((*SendCoinsRequest)(nil), "lnrpc.SendCoinsRequest")
	proto.RegisterType((*SendCoinsResponse)(nil), "lnrpc.SendCoinsResponse")
	proto.RegisterType((*NewAddressRequest)(nil), "lnrpc.NewAddressRequest")
	proto.RegisterType((*NewWitnessAddressRequest)(nil), "lnrpc.NewWitnessAddressRequest")
	proto.RegisterType((*NewAddressResponse)(nil), "lnrpc.NewAddressResponse")
	proto.RegisterType((*ConnectPeerRequest)(nil), "lnrpc.ConnectPeerRequest")
	proto.RegisterType((*ConnectPeerResponse)(nil), "lnrpc.ConnectPeerResponse")
	proto.RegisterType((*HTLC)(nil), "lnrpc.HTLC")
	proto.RegisterType((*ActiveChannel)(nil), "lnrpc.ActiveChannel")
	proto.RegisterType((*ListChannelsRequest)(nil), "lnrpc.ListChannelsRequest")
	proto.RegisterType((*ListChannelsResponse)(nil), "lnrpc.ListChannelsResponse")
	proto.RegisterType((*Peer)(nil), "lnrpc.Peer")
	proto.RegisterType((*ListPeersRequest)(nil), "lnrpc.ListPeersRequest")
	proto.RegisterType((*ListPeersResponse)(nil), "lnrpc.ListPeersResponse")
	proto.RegisterType((*GetInfoRequest)(nil), "lnrpc.GetInfoRequest")
	proto.RegisterType((*GetInfoResponse)(nil), "lnrpc.GetInfoResponse")
	proto.RegisterType((*ConfirmationUpdate)(nil), "lnrpc.ConfirmationUpdate")
	proto.RegisterType((*ChannelOpenUpdate)(nil), "lnrpc.ChannelOpenUpdate")
	proto.RegisterType((*ChannelCloseUpdate)(nil), "lnrpc.ChannelCloseUpdate")
	proto.RegisterType((*CloseChannelRequest)(nil), "lnrpc.CloseChannelRequest")
	proto.RegisterType((*CloseStatusUpdate)(nil), "lnrpc.CloseStatusUpdate")
	proto.RegisterType((*PendingUpdate)(nil), "lnrpc.PendingUpdate")
	proto.RegisterType((*OpenChannelRequest)(nil), "lnrpc.OpenChannelRequest")
	proto.RegisterType((*OpenStatusUpdate)(nil), "lnrpc.OpenStatusUpdate")
	proto.RegisterType((*PendingChannelRequest)(nil), "lnrpc.PendingChannelRequest")
	proto.RegisterType((*PendingChannelResponse)(nil), "lnrpc.PendingChannelResponse")
	proto.RegisterType((*PendingChannelResponse_PendingChannel)(nil), "lnrpc.PendingChannelResponse.PendingChannel")
	proto.RegisterType((*WalletBalanceRequest)(nil), "lnrpc.WalletBalanceRequest")
	proto.RegisterType((*WalletBalanceResponse)(nil), "lnrpc.WalletBalanceResponse")
	proto.RegisterType((*ChannelBalanceRequest)(nil), "lnrpc.ChannelBalanceRequest")
	proto.RegisterType((*ChannelBalanceResponse)(nil), "lnrpc.ChannelBalanceResponse")
	proto.RegisterType((*RoutingTableLink)(nil), "lnrpc.RoutingTableLink")
	proto.RegisterType((*ShowRoutingTableRequest)(nil), "lnrpc.ShowRoutingTableRequest")
	proto.RegisterType((*ShowRoutingTableResponse)(nil), "lnrpc.ShowRoutingTableResponse")
	proto.RegisterType((*Invoice)(nil), "lnrpc.Invoice")
	proto.RegisterType((*AddInvoiceResponse)(nil), "lnrpc.AddInvoiceResponse")
	proto.RegisterType((*PaymentHash)(nil), "lnrpc.PaymentHash")
	proto.RegisterType((*ListInvoiceRequest)(nil), "lnrpc.ListInvoiceRequest")
	proto.RegisterType((*ListInvoiceResponse)(nil), "lnrpc.ListInvoiceResponse")
	proto.RegisterType((*InvoiceSubscription)(nil), "lnrpc.InvoiceSubscription")
	proto.RegisterEnum("lnrpc.ChannelStatus", ChannelStatus_name, ChannelStatus_value)
	proto.RegisterEnum("lnrpc.NewAddressRequest_AddressType", NewAddressRequest_AddressType_name, NewAddressRequest_AddressType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for Lightning service

type LightningClient interface {
	WalletBalance(ctx context.Context, in *WalletBalanceRequest, opts ...grpc.CallOption) (*WalletBalanceResponse, error)
	ChannelBalance(ctx context.Context, in *ChannelBalanceRequest, opts ...grpc.CallOption) (*ChannelBalanceResponse, error)
	GetTransactions(ctx context.Context, in *GetTransactionsRequest, opts ...grpc.CallOption) (*TransactionDetails, error)
	SendCoins(ctx context.Context, in *SendCoinsRequest, opts ...grpc.CallOption) (*SendCoinsResponse, error)
	SubscribeTransactions(ctx context.Context, in *GetTransactionsRequest, opts ...grpc.CallOption) (Lightning_SubscribeTransactionsClient, error)
	SendMany(ctx context.Context, in *SendManyRequest, opts ...grpc.CallOption) (*SendManyResponse, error)
	NewAddress(ctx context.Context, in *NewAddressRequest, opts ...grpc.CallOption) (*NewAddressResponse, error)
	NewWitnessAddress(ctx context.Context, in *NewWitnessAddressRequest, opts ...grpc.CallOption) (*NewAddressResponse, error)
	ConnectPeer(ctx context.Context, in *ConnectPeerRequest, opts ...grpc.CallOption) (*ConnectPeerResponse, error)
	ListPeers(ctx context.Context, in *ListPeersRequest, opts ...grpc.CallOption) (*ListPeersResponse, error)
	GetInfo(ctx context.Context, in *GetInfoRequest, opts ...grpc.CallOption) (*GetInfoResponse, error)
	// TODO(roasbeef): merge with below with bool?
	PendingChannels(ctx context.Context, in *PendingChannelRequest, opts ...grpc.CallOption) (*PendingChannelResponse, error)
	ListChannels(ctx context.Context, in *ListChannelsRequest, opts ...grpc.CallOption) (*ListChannelsResponse, error)
	OpenChannelSync(ctx context.Context, in *OpenChannelRequest, opts ...grpc.CallOption) (*ChannelPoint, error)
	OpenChannel(ctx context.Context, in *OpenChannelRequest, opts ...grpc.CallOption) (Lightning_OpenChannelClient, error)
	CloseChannel(ctx context.Context, in *CloseChannelRequest, opts ...grpc.CallOption) (Lightning_CloseChannelClient, error)
	SendPayment(ctx context.Context, opts ...grpc.CallOption) (Lightning_SendPaymentClient, error)
	SendPaymentSync(ctx context.Context, in *SendRequest, opts ...grpc.CallOption) (*SendResponse, error)
	AddInvoice(ctx context.Context, in *Invoice, opts ...grpc.CallOption) (*AddInvoiceResponse, error)
	ListInvoices(ctx context.Context, in *ListInvoiceRequest, opts ...grpc.CallOption) (*ListInvoiceResponse, error)
	LookupInvoice(ctx context.Context, in *PaymentHash, opts ...grpc.CallOption) (*Invoice, error)
	SubscribeInvoices(ctx context.Context, in *InvoiceSubscription, opts ...grpc.CallOption) (Lightning_SubscribeInvoicesClient, error)
	ShowRoutingTable(ctx context.Context, in *ShowRoutingTableRequest, opts ...grpc.CallOption) (*ShowRoutingTableResponse, error)
}

type lightningClient struct {
	cc *grpc.ClientConn
}

func NewLightningClient(cc *grpc.ClientConn) LightningClient {
	return &lightningClient{cc}
}

func (c *lightningClient) WalletBalance(ctx context.Context, in *WalletBalanceRequest, opts ...grpc.CallOption) (*WalletBalanceResponse, error) {
	out := new(WalletBalanceResponse)
	err := grpc.Invoke(ctx, "/lnrpc.Lightning/WalletBalance", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lightningClient) ChannelBalance(ctx context.Context, in *ChannelBalanceRequest, opts ...grpc.CallOption) (*ChannelBalanceResponse, error) {
	out := new(ChannelBalanceResponse)
	err := grpc.Invoke(ctx, "/lnrpc.Lightning/ChannelBalance", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lightningClient) GetTransactions(ctx context.Context, in *GetTransactionsRequest, opts ...grpc.CallOption) (*TransactionDetails, error) {
	out := new(TransactionDetails)
	err := grpc.Invoke(ctx, "/lnrpc.Lightning/GetTransactions", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lightningClient) SendCoins(ctx context.Context, in *SendCoinsRequest, opts ...grpc.CallOption) (*SendCoinsResponse, error) {
	out := new(SendCoinsResponse)
	err := grpc.Invoke(ctx, "/lnrpc.Lightning/SendCoins", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lightningClient) SubscribeTransactions(ctx context.Context, in *GetTransactionsRequest, opts ...grpc.CallOption) (Lightning_SubscribeTransactionsClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Lightning_serviceDesc.Streams[0], c.cc, "/lnrpc.Lightning/SubscribeTransactions", opts...)
	if err != nil {
		return nil, err
	}
	x := &lightningSubscribeTransactionsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Lightning_SubscribeTransactionsClient interface {
	Recv() (*Transaction, error)
	grpc.ClientStream
}

type lightningSubscribeTransactionsClient struct {
	grpc.ClientStream
}

func (x *lightningSubscribeTransactionsClient) Recv() (*Transaction, error) {
	m := new(Transaction)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *lightningClient) SendMany(ctx context.Context, in *SendManyRequest, opts ...grpc.CallOption) (*SendManyResponse, error) {
	out := new(SendManyResponse)
	err := grpc.Invoke(ctx, "/lnrpc.Lightning/SendMany", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lightningClient) NewAddress(ctx context.Context, in *NewAddressRequest, opts ...grpc.CallOption) (*NewAddressResponse, error) {
	out := new(NewAddressResponse)
	err := grpc.Invoke(ctx, "/lnrpc.Lightning/NewAddress", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lightningClient) NewWitnessAddress(ctx context.Context, in *NewWitnessAddressRequest, opts ...grpc.CallOption) (*NewAddressResponse, error) {
	out := new(NewAddressResponse)
	err := grpc.Invoke(ctx, "/lnrpc.Lightning/NewWitnessAddress", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lightningClient) ConnectPeer(ctx context.Context, in *ConnectPeerRequest, opts ...grpc.CallOption) (*ConnectPeerResponse, error) {
	out := new(ConnectPeerResponse)
	err := grpc.Invoke(ctx, "/lnrpc.Lightning/ConnectPeer", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lightningClient) ListPeers(ctx context.Context, in *ListPeersRequest, opts ...grpc.CallOption) (*ListPeersResponse, error) {
	out := new(ListPeersResponse)
	err := grpc.Invoke(ctx, "/lnrpc.Lightning/ListPeers", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lightningClient) GetInfo(ctx context.Context, in *GetInfoRequest, opts ...grpc.CallOption) (*GetInfoResponse, error) {
	out := new(GetInfoResponse)
	err := grpc.Invoke(ctx, "/lnrpc.Lightning/GetInfo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lightningClient) PendingChannels(ctx context.Context, in *PendingChannelRequest, opts ...grpc.CallOption) (*PendingChannelResponse, error) {
	out := new(PendingChannelResponse)
	err := grpc.Invoke(ctx, "/lnrpc.Lightning/PendingChannels", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lightningClient) ListChannels(ctx context.Context, in *ListChannelsRequest, opts ...grpc.CallOption) (*ListChannelsResponse, error) {
	out := new(ListChannelsResponse)
	err := grpc.Invoke(ctx, "/lnrpc.Lightning/ListChannels", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lightningClient) OpenChannelSync(ctx context.Context, in *OpenChannelRequest, opts ...grpc.CallOption) (*ChannelPoint, error) {
	out := new(ChannelPoint)
	err := grpc.Invoke(ctx, "/lnrpc.Lightning/OpenChannelSync", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lightningClient) OpenChannel(ctx context.Context, in *OpenChannelRequest, opts ...grpc.CallOption) (Lightning_OpenChannelClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Lightning_serviceDesc.Streams[1], c.cc, "/lnrpc.Lightning/OpenChannel", opts...)
	if err != nil {
		return nil, err
	}
	x := &lightningOpenChannelClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Lightning_OpenChannelClient interface {
	Recv() (*OpenStatusUpdate, error)
	grpc.ClientStream
}

type lightningOpenChannelClient struct {
	grpc.ClientStream
}

func (x *lightningOpenChannelClient) Recv() (*OpenStatusUpdate, error) {
	m := new(OpenStatusUpdate)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *lightningClient) CloseChannel(ctx context.Context, in *CloseChannelRequest, opts ...grpc.CallOption) (Lightning_CloseChannelClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Lightning_serviceDesc.Streams[2], c.cc, "/lnrpc.Lightning/CloseChannel", opts...)
	if err != nil {
		return nil, err
	}
	x := &lightningCloseChannelClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Lightning_CloseChannelClient interface {
	Recv() (*CloseStatusUpdate, error)
	grpc.ClientStream
}

type lightningCloseChannelClient struct {
	grpc.ClientStream
}

func (x *lightningCloseChannelClient) Recv() (*CloseStatusUpdate, error) {
	m := new(CloseStatusUpdate)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *lightningClient) SendPayment(ctx context.Context, opts ...grpc.CallOption) (Lightning_SendPaymentClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Lightning_serviceDesc.Streams[3], c.cc, "/lnrpc.Lightning/SendPayment", opts...)
	if err != nil {
		return nil, err
	}
	x := &lightningSendPaymentClient{stream}
	return x, nil
}

type Lightning_SendPaymentClient interface {
	Send(*SendRequest) error
	Recv() (*SendResponse, error)
	grpc.ClientStream
}

type lightningSendPaymentClient struct {
	grpc.ClientStream
}

func (x *lightningSendPaymentClient) Send(m *SendRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *lightningSendPaymentClient) Recv() (*SendResponse, error) {
	m := new(SendResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *lightningClient) SendPaymentSync(ctx context.Context, in *SendRequest, opts ...grpc.CallOption) (*SendResponse, error) {
	out := new(SendResponse)
	err := grpc.Invoke(ctx, "/lnrpc.Lightning/SendPaymentSync", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lightningClient) AddInvoice(ctx context.Context, in *Invoice, opts ...grpc.CallOption) (*AddInvoiceResponse, error) {
	out := new(AddInvoiceResponse)
	err := grpc.Invoke(ctx, "/lnrpc.Lightning/AddInvoice", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lightningClient) ListInvoices(ctx context.Context, in *ListInvoiceRequest, opts ...grpc.CallOption) (*ListInvoiceResponse, error) {
	out := new(ListInvoiceResponse)
	err := grpc.Invoke(ctx, "/lnrpc.Lightning/ListInvoices", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lightningClient) LookupInvoice(ctx context.Context, in *PaymentHash, opts ...grpc.CallOption) (*Invoice, error) {
	out := new(Invoice)
	err := grpc.Invoke(ctx, "/lnrpc.Lightning/LookupInvoice", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lightningClient) SubscribeInvoices(ctx context.Context, in *InvoiceSubscription, opts ...grpc.CallOption) (Lightning_SubscribeInvoicesClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Lightning_serviceDesc.Streams[4], c.cc, "/lnrpc.Lightning/SubscribeInvoices", opts...)
	if err != nil {
		return nil, err
	}
	x := &lightningSubscribeInvoicesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Lightning_SubscribeInvoicesClient interface {
	Recv() (*Invoice, error)
	grpc.ClientStream
}

type lightningSubscribeInvoicesClient struct {
	grpc.ClientStream
}

func (x *lightningSubscribeInvoicesClient) Recv() (*Invoice, error) {
	m := new(Invoice)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *lightningClient) ShowRoutingTable(ctx context.Context, in *ShowRoutingTableRequest, opts ...grpc.CallOption) (*ShowRoutingTableResponse, error) {
	out := new(ShowRoutingTableResponse)
	err := grpc.Invoke(ctx, "/lnrpc.Lightning/ShowRoutingTable", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Lightning service

type LightningServer interface {
	WalletBalance(context.Context, *WalletBalanceRequest) (*WalletBalanceResponse, error)
	ChannelBalance(context.Context, *ChannelBalanceRequest) (*ChannelBalanceResponse, error)
	GetTransactions(context.Context, *GetTransactionsRequest) (*TransactionDetails, error)
	SendCoins(context.Context, *SendCoinsRequest) (*SendCoinsResponse, error)
	SubscribeTransactions(*GetTransactionsRequest, Lightning_SubscribeTransactionsServer) error
	SendMany(context.Context, *SendManyRequest) (*SendManyResponse, error)
	NewAddress(context.Context, *NewAddressRequest) (*NewAddressResponse, error)
	NewWitnessAddress(context.Context, *NewWitnessAddressRequest) (*NewAddressResponse, error)
	ConnectPeer(context.Context, *ConnectPeerRequest) (*ConnectPeerResponse, error)
	ListPeers(context.Context, *ListPeersRequest) (*ListPeersResponse, error)
	GetInfo(context.Context, *GetInfoRequest) (*GetInfoResponse, error)
	// TODO(roasbeef): merge with below with bool?
	PendingChannels(context.Context, *PendingChannelRequest) (*PendingChannelResponse, error)
	ListChannels(context.Context, *ListChannelsRequest) (*ListChannelsResponse, error)
	OpenChannelSync(context.Context, *OpenChannelRequest) (*ChannelPoint, error)
	OpenChannel(*OpenChannelRequest, Lightning_OpenChannelServer) error
	CloseChannel(*CloseChannelRequest, Lightning_CloseChannelServer) error
	SendPayment(Lightning_SendPaymentServer) error
	SendPaymentSync(context.Context, *SendRequest) (*SendResponse, error)
	AddInvoice(context.Context, *Invoice) (*AddInvoiceResponse, error)
	ListInvoices(context.Context, *ListInvoiceRequest) (*ListInvoiceResponse, error)
	LookupInvoice(context.Context, *PaymentHash) (*Invoice, error)
	SubscribeInvoices(*InvoiceSubscription, Lightning_SubscribeInvoicesServer) error
	ShowRoutingTable(context.Context, *ShowRoutingTableRequest) (*ShowRoutingTableResponse, error)
}

func RegisterLightningServer(s *grpc.Server, srv LightningServer) {
	s.RegisterService(&_Lightning_serviceDesc, srv)
}

func _Lightning_WalletBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WalletBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LightningServer).WalletBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lnrpc.Lightning/WalletBalance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LightningServer).WalletBalance(ctx, req.(*WalletBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Lightning_ChannelBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChannelBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LightningServer).ChannelBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lnrpc.Lightning/ChannelBalance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LightningServer).ChannelBalance(ctx, req.(*ChannelBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Lightning_GetTransactions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTransactionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LightningServer).GetTransactions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lnrpc.Lightning/GetTransactions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LightningServer).GetTransactions(ctx, req.(*GetTransactionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Lightning_SendCoins_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendCoinsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LightningServer).SendCoins(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lnrpc.Lightning/SendCoins",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LightningServer).SendCoins(ctx, req.(*SendCoinsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Lightning_SubscribeTransactions_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetTransactionsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LightningServer).SubscribeTransactions(m, &lightningSubscribeTransactionsServer{stream})
}

type Lightning_SubscribeTransactionsServer interface {
	Send(*Transaction) error
	grpc.ServerStream
}

type lightningSubscribeTransactionsServer struct {
	grpc.ServerStream
}

func (x *lightningSubscribeTransactionsServer) Send(m *Transaction) error {
	return x.ServerStream.SendMsg(m)
}

func _Lightning_SendMany_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendManyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LightningServer).SendMany(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lnrpc.Lightning/SendMany",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LightningServer).SendMany(ctx, req.(*SendManyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Lightning_NewAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LightningServer).NewAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lnrpc.Lightning/NewAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LightningServer).NewAddress(ctx, req.(*NewAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Lightning_NewWitnessAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewWitnessAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LightningServer).NewWitnessAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lnrpc.Lightning/NewWitnessAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LightningServer).NewWitnessAddress(ctx, req.(*NewWitnessAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Lightning_ConnectPeer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectPeerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LightningServer).ConnectPeer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lnrpc.Lightning/ConnectPeer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LightningServer).ConnectPeer(ctx, req.(*ConnectPeerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Lightning_ListPeers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPeersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LightningServer).ListPeers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lnrpc.Lightning/ListPeers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LightningServer).ListPeers(ctx, req.(*ListPeersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Lightning_GetInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LightningServer).GetInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lnrpc.Lightning/GetInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LightningServer).GetInfo(ctx, req.(*GetInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Lightning_PendingChannels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PendingChannelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LightningServer).PendingChannels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lnrpc.Lightning/PendingChannels",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LightningServer).PendingChannels(ctx, req.(*PendingChannelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Lightning_ListChannels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListChannelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LightningServer).ListChannels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lnrpc.Lightning/ListChannels",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LightningServer).ListChannels(ctx, req.(*ListChannelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Lightning_OpenChannelSync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpenChannelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LightningServer).OpenChannelSync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lnrpc.Lightning/OpenChannelSync",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LightningServer).OpenChannelSync(ctx, req.(*OpenChannelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Lightning_OpenChannel_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(OpenChannelRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LightningServer).OpenChannel(m, &lightningOpenChannelServer{stream})
}

type Lightning_OpenChannelServer interface {
	Send(*OpenStatusUpdate) error
	grpc.ServerStream
}

type lightningOpenChannelServer struct {
	grpc.ServerStream
}

func (x *lightningOpenChannelServer) Send(m *OpenStatusUpdate) error {
	return x.ServerStream.SendMsg(m)
}

func _Lightning_CloseChannel_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CloseChannelRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LightningServer).CloseChannel(m, &lightningCloseChannelServer{stream})
}

type Lightning_CloseChannelServer interface {
	Send(*CloseStatusUpdate) error
	grpc.ServerStream
}

type lightningCloseChannelServer struct {
	grpc.ServerStream
}

func (x *lightningCloseChannelServer) Send(m *CloseStatusUpdate) error {
	return x.ServerStream.SendMsg(m)
}

func _Lightning_SendPayment_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(LightningServer).SendPayment(&lightningSendPaymentServer{stream})
}

type Lightning_SendPaymentServer interface {
	Send(*SendResponse) error
	Recv() (*SendRequest, error)
	grpc.ServerStream
}

type lightningSendPaymentServer struct {
	grpc.ServerStream
}

func (x *lightningSendPaymentServer) Send(m *SendResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *lightningSendPaymentServer) Recv() (*SendRequest, error) {
	m := new(SendRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Lightning_SendPaymentSync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LightningServer).SendPaymentSync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lnrpc.Lightning/SendPaymentSync",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LightningServer).SendPaymentSync(ctx, req.(*SendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Lightning_AddInvoice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Invoice)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LightningServer).AddInvoice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lnrpc.Lightning/AddInvoice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LightningServer).AddInvoice(ctx, req.(*Invoice))
	}
	return interceptor(ctx, in, info, handler)
}

func _Lightning_ListInvoices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListInvoiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LightningServer).ListInvoices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lnrpc.Lightning/ListInvoices",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LightningServer).ListInvoices(ctx, req.(*ListInvoiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Lightning_LookupInvoice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PaymentHash)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LightningServer).LookupInvoice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lnrpc.Lightning/LookupInvoice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LightningServer).LookupInvoice(ctx, req.(*PaymentHash))
	}
	return interceptor(ctx, in, info, handler)
}

func _Lightning_SubscribeInvoices_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(InvoiceSubscription)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LightningServer).SubscribeInvoices(m, &lightningSubscribeInvoicesServer{stream})
}

type Lightning_SubscribeInvoicesServer interface {
	Send(*Invoice) error
	grpc.ServerStream
}

type lightningSubscribeInvoicesServer struct {
	grpc.ServerStream
}

func (x *lightningSubscribeInvoicesServer) Send(m *Invoice) error {
	return x.ServerStream.SendMsg(m)
}

func _Lightning_ShowRoutingTable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShowRoutingTableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LightningServer).ShowRoutingTable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lnrpc.Lightning/ShowRoutingTable",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LightningServer).ShowRoutingTable(ctx, req.(*ShowRoutingTableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Lightning_serviceDesc = grpc.ServiceDesc{
	ServiceName: "lnrpc.Lightning",
	HandlerType: (*LightningServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "WalletBalance",
			Handler:    _Lightning_WalletBalance_Handler,
		},
		{
			MethodName: "ChannelBalance",
			Handler:    _Lightning_ChannelBalance_Handler,
		},
		{
			MethodName: "GetTransactions",
			Handler:    _Lightning_GetTransactions_Handler,
		},
		{
			MethodName: "SendCoins",
			Handler:    _Lightning_SendCoins_Handler,
		},
		{
			MethodName: "SendMany",
			Handler:    _Lightning_SendMany_Handler,
		},
		{
			MethodName: "NewAddress",
			Handler:    _Lightning_NewAddress_Handler,
		},
		{
			MethodName: "NewWitnessAddress",
			Handler:    _Lightning_NewWitnessAddress_Handler,
		},
		{
			MethodName: "ConnectPeer",
			Handler:    _Lightning_ConnectPeer_Handler,
		},
		{
			MethodName: "ListPeers",
			Handler:    _Lightning_ListPeers_Handler,
		},
		{
			MethodName: "GetInfo",
			Handler:    _Lightning_GetInfo_Handler,
		},
		{
			MethodName: "PendingChannels",
			Handler:    _Lightning_PendingChannels_Handler,
		},
		{
			MethodName: "ListChannels",
			Handler:    _Lightning_ListChannels_Handler,
		},
		{
			MethodName: "OpenChannelSync",
			Handler:    _Lightning_OpenChannelSync_Handler,
		},
		{
			MethodName: "SendPaymentSync",
			Handler:    _Lightning_SendPaymentSync_Handler,
		},
		{
			MethodName: "AddInvoice",
			Handler:    _Lightning_AddInvoice_Handler,
		},
		{
			MethodName: "ListInvoices",
			Handler:    _Lightning_ListInvoices_Handler,
		},
		{
			MethodName: "LookupInvoice",
			Handler:    _Lightning_LookupInvoice_Handler,
		},
		{
			MethodName: "ShowRoutingTable",
			Handler:    _Lightning_ShowRoutingTable_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeTransactions",
			Handler:       _Lightning_SubscribeTransactions_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "OpenChannel",
			Handler:       _Lightning_OpenChannel_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "CloseChannel",
			Handler:       _Lightning_CloseChannel_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SendPayment",
			Handler:       _Lightning_SendPayment_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "SubscribeInvoices",
			Handler:       _Lightning_SubscribeInvoices_Handler,
			ServerStreams: true,
		},
	},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("rpc.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 2318 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xb4, 0x59, 0xcb, 0x6e, 0x24, 0x57,
	0x19, 0x9e, 0xee, 0x76, 0xdb, 0xee, 0xbf, 0x2f, 0xee, 0x3e, 0xbe, 0xb5, 0xcb, 0x9e, 0x4b, 0x0e,
	0x93, 0xc8, 0xb1, 0x26, 0x76, 0xc6, 0x59, 0x80, 0x26, 0x22, 0xc8, 0xe3, 0x98, 0x78, 0x84, 0xe3,
	0x31, 0x69, 0x4f, 0x46, 0x80, 0x50, 0xa7, 0xdc, 0x7d, 0x6c, 0x57, 0x5c, 0x5d, 0x55, 0x54, 0x55,
	0xdb, 0x63, 0xa2, 0xd9, 0x80, 0xc4, 0x1a, 0x09, 0x09, 0x21, 0x21, 0xf1, 0x04, 0x08, 0xf1, 0x02,
	0x6c, 0xd9, 0xb0, 0x64, 0xc3, 0x03, 0xf0, 0x20, 0xfc, 0xe7, 0x56, 0x75, 0xea, 0x32, 0x23, 0xb2,
	0xc8, 0x6a, 0xa6, 0xff, 0x73, 0xce, 0xf7, 0xdf, 0x6f, 0x65, 0x68, 0x84, 0xc1, 0x68, 0x3b, 0x08,
	0xfd, 0xd8, 0x27, 0x75, 0xd7, 0xc3, 0x1f, 0xd6, 0xc6, 0x85, 0xef, 0x5f, 0xb8, 0x6c, 0xc7, 0x0e,
	0x9c, 0x1d, 0xdb, 0xf3, 0xfc, 0xd8, 0x8e, 0x1d, 0xdf, 0x8b, 0xe4, 0x25, 0xfa, 0xe7, 0x0a, 0x34,
	0x4f, 0x43, 0xdb, 0x8b, 0xec, 0x11, 0x27, 0x93, 0x05, 0x98, 0x8b, 0x5f, 0x0d, 0x2f, 0xed, 0xe8,
	0xb2, 0x5f, 0x79, 0x50, 0xd9, 0x6c, 0x90, 0x0e, 0xcc, 0xda, 0x13, 0x7f, 0xea, 0xc5, 0xfd, 0x2a,
	0xfe, 0xae, 0x90, 0x35, 0xe8, 0x79, 0xd3, 0xc9, 0x70, 0xe4, 0x7b, 0xe7, 0x4e, 0x38, 0x91, 0x58,
	0xfd, 0x1a, 0x1e, 0xd5, 0x09, 0x01, 0x38, 0x73, 0xfd, 0xd1, 0x95, 0x7c, 0x3e, 0x23, 0x9e, 0x2f,
	0x41, 0x4b, 0xd1, 0x98, 0x73, 0x71, 0x19, 0xf7, 0xeb, 0xfa, 0x66, 0xec, 0x4c, 0xd8, 0x30, 0x8a,
	0xed, 0x49, 0xd0, 0x9f, 0x45, 0x5a, 0x4d, 0xd0, 0x50, 0x38, 0x77, 0x78, 0xce, 0x58, 0xd4, 0x9f,
	0xe3, 0x34, 0xda, 0x87, 0x95, 0xcf, 0x58, 0x6c, 0xc8, 0x17, 0x7d, 0xc1, 0x7e, 0x35, 0x65, 0x51,
	0x4c, 0x3f, 0x01, 0x62, 0x90, 0x3f, 0x65, 0xb1, 0xed, 0xb8, 0x11, 0xd9, 0x84, 0x56, 0x6c, 0x5c,
	0x46, 0x15, 0x6a, 0x9b, 0xcd, 0x5d, 0xb2, 0x2d, 0x2c, 0xb1, 0x6d, 0x3c, 0xa0, 0xbf, 0x45, 0xbd,
	0x07, 0xcc, 0x1b, 0x2b, 0x3c, 0xd2, 0x82, 0x99, 0x31, 0xfe, 0x2b, 0x94, 0x6e, 0x91, 0x45, 0x68,
	0xf2, 0x5f, 0x28, 0x5f, 0xe8, 0x78, 0x17, 0x42, 0xf3, 0x06, 0x69, 0x42, 0xcd, 0x9e, 0xc4, 0x42,
	0xd7, 0x1a, 0xd7, 0x2b, 0xb0, 0x6f, 0x27, 0xcc, 0x8b, 0x53, 0x6d, 0x5b, 0x64, 0x1d, 0x16, 0x4d,
	0xaa, 0x7e, 0x5f, 0x17, 0xef, 0x7b, 0xd0, 0x38, 0xb7, 0x39, 0x28, 0xb2, 0x15, 0x3a, 0xcf, 0xd3,
	0x0e, 0xb4, 0xa4, 0x10, 0x51, 0x80, 0xe2, 0x32, 0x7a, 0x0a, 0xad, 0xfd, 0x4b, 0x74, 0x12, 0x73,
	0x4f, 0x7c, 0xc7, 0x8b, 0x39, 0x97, 0xf3, 0xa9, 0x37, 0x46, 0x8c, 0x61, 0xfc, 0xca, 0x19, 0x2b,
	0xe9, 0xfa, 0xd0, 0x35, 0xa9, 0x9c, 0x8b, 0x12, 0x11, 0xef, 0xfb, 0xd3, 0x38, 0x98, 0xc6, 0x43,
	0xc7, 0x1b, 0xb3, 0x57, 0x42, 0xd6, 0x36, 0xfd, 0x10, 0xba, 0x47, 0xdc, 0xf8, 0x1e, 0xbe, 0xd8,
	0x1b, 0x8f, 0x43, 0x16, 0x45, 0xdc, 0xad, 0xc1, 0xf4, 0xec, 0x8a, 0xdd, 0x2a, 0x37, 0xa3, 0xfe,
	0x97, 0x7e, 0x24, 0x9d, 0xdc, 0xa0, 0xbf, 0xab, 0xc0, 0x02, 0x17, 0xec, 0x73, 0xdb, 0xbb, 0xd5,
	0x16, 0xfa, 0x04, 0x5a, 0xfc, 0xf1, 0xa9, 0xbf, 0x27, 0xc3, 0x41, 0xda, 0x76, 0x53, 0xd9, 0x36,
	0x77, 0x7b, 0xdb, 0xbc, 0x7a, 0xe0, 0xc5, 0xe1, 0xad, 0xf5, 0x11, 0xf4, 0x0a, 0x44, 0x6e, 0xd3,
	0x54, 0x86, 0x36, 0xd4, 0xaf, 0x6d, 0x77, 0xca, 0x84, 0x10, 0xb5, 0x27, 0xd5, 0x1f, 0x54, 0xe8,
	0x03, 0xe8, 0xa6, 0xc8, 0xd2, 0x48, 0x5c, 0xd4, 0xc4, 0x18, 0x0d, 0xae, 0x1c, 0xbf, 0xb1, 0x8f,
	0xf6, 0x8a, 0x0c, 0x67, 0xda, 0xc8, 0xaa, 0x34, 0x82, 0x6b, 0xf4, 0x1d, 0xe8, 0x19, 0x2f, 0x4a,
	0x41, 0xff, 0x54, 0x81, 0xde, 0x31, 0xbb, 0x51, 0xc6, 0xd2, 0xb0, 0xbb, 0x78, 0xe7, 0x36, 0x60,
	0xe2, 0x4e, 0x67, 0xf7, 0xa1, 0xd2, 0xbc, 0x70, 0x6f, 0x5b, 0xfd, 0x3c, 0xc5, 0xbb, 0xf4, 0x39,
	0x34, 0x8d, 0x9f, 0x64, 0x15, 0x16, 0x5f, 0x3e, 0x3b, 0x3d, 0x3e, 0x18, 0x0c, 0x86, 0x27, 0x2f,
	0x9e, 0xfe, 0xe4, 0xe0, 0x67, 0xc3, 0xc3, 0xbd, 0xc1, 0x61, 0xf7, 0x0e, 0x59, 0x01, 0x82, 0xd4,
	0xd3, 0x83, 0x4f, 0x33, 0xf4, 0x0a, 0xe6, 0x63, 0xd3, 0x24, 0x54, 0xa9, 0x05, 0x7d, 0xe4, 0xf8,
	0xd2, 0x89, 0x3d, 0xc4, 0xcc, 0x32, 0xa6, 0xef, 0x22, 0x88, 0x21, 0x8d, 0x52, 0x0d, 0x53, 0xda,
	0x96, 0x24, 0xa5, 0xdd, 0xc7, 0x40, 0xf6, 0x7d, 0x0c, 0xb2, 0x51, 0x7c, 0xc2, 0x58, 0xa8, 0xb5,
	0x7b, 0xd7, 0x30, 0x5a, 0x73, 0x77, 0x55, 0x69, 0x97, 0x0f, 0x1c, 0xfa, 0x1e, 0x2c, 0x66, 0x1e,
	0xa7, 0x4c, 0x02, 0xfc, 0x3d, 0x54, 0x26, 0xac, 0xd3, 0x00, 0x66, 0x0e, 0x4f, 0x8f, 0xf6, 0x49,
	0x17, 0xe6, 0x1d, 0x6f, 0xe4, 0x4f, 0x78, 0x1e, 0xf0, 0x93, 0xf9, 0xbc, 0x3f, 0x78, 0x5e, 0x88,
	0x64, 0xe1, 0x65, 0x42, 0x44, 0x6c, 0x8b, 0x17, 0x19, 0xf6, 0x2a, 0x70, 0x42, 0x51, 0x5e, 0x74,
	0xe9, 0xe0, 0x29, 0xd6, 0xe6, 0xc1, 0x1f, 0xb2, 0x6b, 0x7f, 0x24, 0x8f, 0xc6, 0xcc, 0xb5, 0x6f,
	0x45, 0x7e, 0xb5, 0xe9, 0xef, 0xab, 0xd0, 0xde, 0xc3, 0xec, 0xbe, 0x66, 0x2a, 0x87, 0xc8, 0x32,
	0xb4, 0x43, 0x36, 0xf1, 0x63, 0x36, 0xcc, 0xc4, 0x3a, 0x92, 0x47, 0xf2, 0xc6, 0x30, 0xe0, 0x69,
	0xa6, 0x92, 0x07, 0x25, 0x1d, 0xd9, 0x81, 0x3d, 0x72, 0xe2, 0x5b, 0x95, 0xe4, 0x78, 0x11, 0x85,
	0xc2, 0x92, 0x74, 0x66, 0xbb, 0xb6, 0x37, 0x62, 0x42, 0x84, 0x1a, 0xfa, 0xaa, 0xa3, 0x60, 0x35,
	0xbd, 0x2e, 0xe8, 0x28, 0xf5, 0x14, 0x6d, 0x11, 0xc7, 0x2e, 0x1b, 0x27, 0x47, 0xb2, 0xb8, 0x61,
	0x61, 0x90, 0xc5, 0x2d, 0xb2, 0x63, 0x3f, 0xba, 0x74, 0x22, 0x5e, 0x05, 0x62, 0x59, 0xe5, 0xc8,
	0x7d, 0x58, 0xcd, 0x1d, 0x86, 0x6c, 0xc4, 0x50, 0x8f, 0x71, 0x7f, 0x5e, 0x5c, 0xc0, 0x72, 0xc4,
	0x6b, 0xee, 0x34, 0x18, 0xdb, 0x31, 0xd6, 0xc6, 0x06, 0x12, 0x67, 0x08, 0x85, 0x76, 0xc0, 0x64,
	0x15, 0xb8, 0x8c, 0xdd, 0x51, 0xd4, 0x07, 0x91, 0x90, 0x4d, 0xe5, 0x38, 0x6e, 0x7c, 0xba, 0x0c,
	0x8b, 0x47, 0x4e, 0x14, 0x2b, 0x7b, 0x18, 0xc5, 0x73, 0x29, 0x4b, 0x56, 0x4e, 0x7c, 0x0f, 0x2d,
	0xa0, 0x68, 0xfd, 0xa6, 0x40, 0x5b, 0x52, 0x68, 0x19, 0xbb, 0xd2, 0x3f, 0x56, 0x60, 0x86, 0x7b,
	0x5f, 0x78, 0x7d, 0x7a, 0x36, 0x4c, 0x4d, 0x6b, 0x84, 0x41, 0x55, 0x54, 0x7a, 0x23, 0xf8, 0x6a,
	0xe2, 0x06, 0x6f, 0x12, 0xb7, 0xa8, 0x85, 0x34, 0xc0, 0x8c, 0x50, 0x25, 0xa1, 0xa1, 0xde, 0xd7,
	0xc2, 0x98, 0x33, 0xdc, 0x1b, 0x68, 0x0e, 0x79, 0x4b, 0xda, 0x50, 0x51, 0xc4, 0x1d, 0x69, 0x38,
	0x04, 0x77, 0xbc, 0x33, 0x0c, 0x25, 0x69, 0xa8, 0x79, 0x4a, 0x78, 0xa5, 0x8b, 0x44, 0x64, 0x26,
	0xca, 0xee, 0x40, 0xcf, 0xa0, 0x29, 0x4d, 0x2d, 0xa8, 0x73, 0x39, 0x75, 0x87, 0xd0, 0x46, 0xe3,
	0x97, 0x68, 0x17, 0x3a, 0xd8, 0x74, 0x9e, 0x79, 0xe7, 0xbe, 0x86, 0xf8, 0x07, 0x96, 0xc3, 0x84,
	0xa4, 0x10, 0xb0, 0xd4, 0xba, 0x3a, 0x37, 0x74, 0xd4, 0x37, 0x30, 0xbf, 0x17, 0x9c, 0x31, 0x8a,
	0x8c, 0x31, 0xa4, 0x63, 0x4e, 0xaa, 0xbd, 0x01, 0x4b, 0xdc, 0x85, 0xda, 0x63, 0x89, 0x99, 0x65,
	0x50, 0x63, 0x78, 0xf0, 0x53, 0x5b, 0x58, 0x39, 0x3d, 0x14, 0x71, 0xcd, 0xf3, 0x43, 0x3e, 0xe5,
	0xf2, 0xce, 0x0a, 0x52, 0xbe, 0xab, 0xce, 0x09, 0x2a, 0x32, 0x8f, 0x6e, 0x31, 0xe6, 0xc6, 0xc3,
	0xd8, 0xe7, 0x20, 0x8e, 0xa7, 0xcc, 0xf2, 0x42, 0x24, 0x7c, 0xd2, 0xaf, 0x5f, 0x88, 0x38, 0xe2,
	0xb8, 0x12, 0x24, 0xba, 0xb4, 0x55, 0x67, 0xc9, 0xe3, 0x4a, 0x1f, 0x62, 0xbc, 0xeb, 0x96, 0x1f,
	0x0d, 0x5d, 0x76, 0x1e, 0xab, 0xbe, 0xf2, 0x23, 0xe8, 0xa9, 0x88, 0x78, 0x8e, 0x7a, 0x29, 0xd4,
	0xad, 0x7c, 0x72, 0xc9, 0x7a, 0xb2, 0xa8, 0x2c, 0x6c, 0xb6, 0x37, 0x51, 0x88, 0xe4, 0xef, 0x7d,
	0xd7, 0x8f, 0x98, 0x42, 0x40, 0x21, 0x46, 0xf8, 0x33, 0xd7, 0xf4, 0xd0, 0xd7, 0xd1, 0x74, 0x34,
	0xe2, 0x81, 0x54, 0x15, 0x4a, 0x8d, 0xb1, 0x10, 0xf1, 0x57, 0x0a, 0x41, 0x97, 0xb1, 0x6f, 0xc1,
	0x3f, 0x19, 0x43, 0x5c, 0x67, 0xe2, 0xe8, 0x6a, 0x84, 0x4d, 0xe8, 0xdc, 0x0f, 0x31, 0x71, 0x6b,
	0x82, 0xcb, 0xdf, 0xb1, 0x13, 0x08, 0x36, 0x03, 0x9c, 0x9b, 0xa6, 0x91, 0x12, 0xf1, 0x03, 0x64,
	0xc2, 0x89, 0xda, 0x9f, 0x8a, 0xc9, 0x52, 0x12, 0x46, 0x82, 0x2a, 0x2f, 0x1f, 0xde, 0x21, 0x8f,
	0x51, 0x23, 0xc3, 0xfe, 0x82, 0x53, 0x73, 0x77, 0x4d, 0x8b, 0x54, 0x70, 0x0d, 0x3e, 0xd9, 0x01,
	0xe0, 0x6a, 0x0c, 0x05, 0x1b, 0x21, 0x8b, 0xf1, 0xa0, 0x60, 0xb3, 0xc3, 0x3b, 0x4f, 0xe7, 0x61,
	0x56, 0xd6, 0x07, 0x7a, 0x17, 0xda, 0x19, 0x01, 0x32, 0xbd, 0xad, 0x45, 0xff, 0x59, 0x01, 0xc2,
	0xfd, 0x95, 0xb3, 0x1b, 0x3a, 0x39, 0xb6, 0xc3, 0x0b, 0x16, 0x0f, 0x33, 0x75, 0x5c, 0xd4, 0x1e,
	0x7f, 0x9c, 0x54, 0xd0, 0xaa, 0x70, 0x86, 0x05, 0xc4, 0x20, 0xea, 0x31, 0x27, 0x89, 0x74, 0x59,
	0x34, 0xf5, 0x8c, 0xa2, 0x8a, 0xbd, 0xac, 0x9d, 0x77, 0x61, 0x59, 0xd5, 0xce, 0xdc, 0xb1, 0x2c,
	0xa1, 0x18, 0xc2, 0xd8, 0x2b, 0x26, 0x4e, 0x14, 0xf1, 0xea, 0x1e, 0x39, 0xbf, 0xd6, 0x05, 0x54,
	0x25, 0x81, 0x88, 0x41, 0x19, 0xee, 0xf4, 0xaf, 0x15, 0xe8, 0x72, 0x45, 0x32, 0x9e, 0x79, 0x84,
	0xa6, 0xe6, 0x76, 0xfb, 0xce, 0x1c, 0xf3, 0x01, 0x34, 0x04, 0x03, 0x1f, 0x39, 0x28, 0xbf, 0xf4,
	0xb3, 0x7e, 0x49, 0x93, 0x21, 0xe3, 0x96, 0x1f, 0xc2, 0xb2, 0x62, 0x9f, 0xb3, 0xfc, 0x43, 0x98,
	0x8d, 0x84, 0x0a, 0x6a, 0xb0, 0x58, 0xca, 0xc2, 0x49, 0xf5, 0xe8, 0xdf, 0xaa, 0xb0, 0x92, 0x7f,
	0xaf, 0x4a, 0xd1, 0x8f, 0xa1, 0x5b, 0xa8, 0x2b, 0xb2, 0xae, 0x3d, 0xca, 0xea, 0x9d, 0x7b, 0x98,
	0x23, 0x5b, 0xff, 0xaa, 0x40, 0x27, 0x4b, 0x2a, 0xb4, 0x75, 0x9e, 0x9c, 0x49, 0x81, 0xd3, 0xf1,
	0x50, 0xd2, 0x51, 0x6b, 0x85, 0x8e, 0x3a, 0x53, 0xde, 0x51, 0xeb, 0x6f, 0xe8, 0xa8, 0xb3, 0x7a,
	0xca, 0xce, 0x94, 0x82, 0x39, 0x01, 0x9b, 0x1a, 0x6c, 0xfe, 0x2d, 0x06, 0x7b, 0x04, 0x4b, 0x2f,
	0x6d, 0xd7, 0x65, 0xf1, 0x53, 0x09, 0xa9, 0xcd, 0x8d, 0x98, 0x37, 0x72, 0x7a, 0x1a, 0xfa, 0x9e,
	0x2b, 0x1b, 0xd7, 0x3c, 0xdd, 0x84, 0xe5, 0xdc, 0xed, 0x74, 0xb0, 0xd1, 0x32, 0xf1, 0x9b, 0x15,
	0xba, 0x0a, 0xcb, 0x8a, 0x51, 0x16, 0x98, 0xbe, 0x0f, 0x2b, 0xf9, 0x83, 0x72, 0x8c, 0x1a, 0xfd,
	0x0a, 0xba, 0x5f, 0xe0, 0xa0, 0x8e, 0x7a, 0x9d, 0xda, 0x67, 0x2e, 0x3b, 0x72, 0xbc, 0x2b, 0x3e,
	0x0a, 0x3b, 0xe3, 0xc7, 0xaa, 0x8f, 0x88, 0x1f, 0xbb, 0xe9, 0x60, 0xc2, 0xa7, 0xfa, 0xb7, 0x1a,
	0x16, 0x87, 0xaa, 0x9b, 0x74, 0xc3, 0xaa, 0xd0, 0x35, 0x58, 0x1d, 0x5c, 0xfa, 0x37, 0x26, 0x17,
	0x2d, 0xe7, 0x01, 0xf4, 0x8b, 0x47, 0x4a, 0xd2, 0xf7, 0x8d, 0x09, 0x40, 0x86, 0x90, 0x1e, 0x04,
	0xf3, 0xf2, 0xf2, 0x19, 0x79, 0xee, 0x99, 0x77, 0xed, 0x3b, 0x23, 0x51, 0x61, 0x26, 0xe8, 0xbf,
	0x74, 0x08, 0x10, 0x03, 0x4c, 0x10, 0xab, 0x72, 0x81, 0x75, 0x36, 0x1c, 0x06, 0x21, 0x73, 0x26,
	0xf6, 0x05, 0x53, 0x23, 0x1e, 0x0a, 0x1c, 0x9a, 0xab, 0x53, 0x32, 0xfc, 0xd7, 0x75, 0x6b, 0x57,
	0x93, 0x94, 0x5c, 0x95, 0x44, 0x88, 0x85, 0x4c, 0x4d, 0x7d, 0x98, 0x4f, 0x6a, 0x04, 0xc0, 0xf2,
	0x24, 0xef, 0x49, 0xa2, 0x98, 0x97, 0xe8, 0x43, 0x20, 0x38, 0xae, 0x2a, 0xe1, 0x12, 0xdd, 0x52,
	0x8e, 0xb2, 0x10, 0x3e, 0xc6, 0xd1, 0x5a, 0x2e, 0x6b, 0x87, 0x48, 0x94, 0x42, 0xea, 0xad, 0x2d,
	0x5d, 0x1d, 0xd4, 0x13, 0xa1, 0x08, 0xdd, 0x02, 0xc2, 0x67, 0x89, 0x04, 0x39, 0x89, 0x28, 0x9d,
	0x7f, 0x46, 0x44, 0x7d, 0x5f, 0xce, 0x5e, 0x79, 0x29, 0x1e, 0xf0, 0x79, 0x58, 0x90, 0xb4, 0x85,
	0x3b, 0xca, 0xc2, 0xea, 0x26, 0x1f, 0xda, 0xd4, 0x7f, 0x07, 0xd3, 0xb3, 0x68, 0x14, 0xa2, 0x1d,
	0x51, 0xe9, 0xad, 0x5d, 0x68, 0x67, 0x02, 0x9c, 0xcc, 0x41, 0x6d, 0xef, 0xe8, 0x08, 0x77, 0x87,
	0x26, 0xcc, 0x3d, 0x3f, 0x39, 0x38, 0x7e, 0x76, 0xfc, 0x19, 0x2e, 0x0c, 0xf8, 0x63, 0xff, 0xe8,
	0xf9, 0x80, 0xff, 0xa8, 0xee, 0xfe, 0xa7, 0x0b, 0x8d, 0x64, 0x82, 0x27, 0x5f, 0x43, 0x3b, 0x13,
	0xe3, 0x64, 0x5d, 0x71, 0x2e, 0xcb, 0x13, 0x6b, 0xa3, 0xfc, 0x50, 0x6d, 0xaa, 0xf7, 0x7e, 0xf3,
	0xef, 0xff, 0xfe, 0xa1, 0xda, 0x27, 0x2b, 0x3b, 0xd7, 0x8f, 0x77, 0x54, 0x70, 0xef, 0x88, 0xd9,
	0x41, 0x0c, 0x1e, 0xe4, 0x0a, 0x3a, 0xd9, 0x64, 0x20, 0x1b, 0xd9, 0x2c, 0xcd, 0x71, 0xbb, 0xfb,
	0x86, 0x53, 0xc5, 0x6e, 0x43, 0xb0, 0x5b, 0x21, 0x4b, 0x26, 0x3b, 0x1d, 0xa9, 0x84, 0x89, 0xf1,
	0xcc, 0xfc, 0x4c, 0x40, 0x34, 0x5e, 0xf9, 0xe7, 0x03, 0x6b, 0xad, 0xf8, 0x49, 0x40, 0x7d, 0x43,
	0xa0, 0x7d, 0xc1, 0x8a, 0x90, 0x2e, 0x67, 0x65, 0x7e, 0x4d, 0x20, 0xbf, 0x80, 0x46, 0xb2, 0x38,
	0x92, 0x55, 0x63, 0xf1, 0x35, 0x97, 0x4f, 0xab, 0x5f, 0x3c, 0x50, 0x4a, 0xac, 0x0b, 0xe4, 0x65,
	0x5a, 0x40, 0x7e, 0x52, 0xd9, 0x22, 0x47, 0xb0, 0xac, 0xdc, 0x7d, 0xc6, 0xbe, 0x8d, 0x26, 0x25,
	0x1f, 0x37, 0x3e, 0xac, 0x90, 0x8f, 0x61, 0x5e, 0xef, 0xcd, 0x64, 0xa5, 0x7c, 0x45, 0xb7, 0x56,
	0x0b, 0x74, 0x15, 0xa2, 0x7b, 0x00, 0xe9, 0x1a, 0x49, 0xfa, 0x6f, 0xda, 0x73, 0x13, 0x23, 0x96,
	0xec, 0x9c, 0x17, 0x62, 0x7f, 0xce, 0x6e, 0xa9, 0xe4, 0x7e, 0x7a, 0xbf, 0x74, 0x7f, 0x7d, 0x0b,
	0x20, 0x5d, 0x11, 0xb6, 0xeb, 0x92, 0x0e, 0xb7, 0x9d, 0xc7, 0x6e, 0xd4, 0x52, 0x41, 0x7e, 0x0e,
	0x4d, 0x63, 0x1d, 0x25, 0x46, 0xeb, 0xce, 0xed, 0xb7, 0x96, 0x55, 0x76, 0xa4, 0xd0, 0x97, 0x04,
	0x7a, 0x87, 0x36, 0x38, 0xba, 0x18, 0xb4, 0xb9, 0x4b, 0x7e, 0xca, 0x93, 0x47, 0x6d, 0x0e, 0x24,
	0x5d, 0x88, 0xb3, 0xfb, 0x45, 0xe2, 0xef, 0xc2, 0x92, 0x41, 0x7b, 0x02, 0xb5, 0x49, 0x52, 0x54,
	0xf2, 0x39, 0xcc, 0xa9, 0x45, 0x82, 0x2c, 0xa7, 0x7e, 0x35, 0x76, 0x0d, 0x6b, 0x25, 0x4f, 0x56,
	0x60, 0x8b, 0x02, 0xac, 0x4d, 0x9a, 0x1c, 0x0c, 0xc7, 0x34, 0x87, 0x63, 0xb8, 0xb0, 0x90, 0x6d,
	0xd8, 0x51, 0x92, 0x66, 0xa5, 0xb3, 0x46, 0x92, 0x66, 0xe5, 0x03, 0x41, 0x36, 0xcd, 0x74, 0x7a,
	0xed, 0xa8, 0xe2, 0x46, 0x7e, 0x09, 0x2d, 0x73, 0x6d, 0x24, 0x96, 0xa1, 0x79, 0x6e, 0xc5, 0xb4,
	0xd6, 0x4b, 0xcf, 0xb2, 0xe6, 0x26, 0x2d, 0x93, 0x0d, 0xba, 0x72, 0xc1, 0x98, 0x4b, 0x07, 0xb8,
	0xc9, 0x24, 0xee, 0x2c, 0xce, 0xab, 0x56, 0xe9, 0x42, 0xb1, 0x2a, 0x80, 0x7b, 0x34, 0x03, 0xcc,
	0x5d, 0xb9, 0x0f, 0x4d, 0x03, 0xe3, 0x6d, 0xb8, 0xab, 0xc6, 0x91, 0x39, 0x59, 0x62, 0x52, 0xfd,
	0xa5, 0x02, 0x2d, 0x73, 0xe5, 0x48, 0x0c, 0x50, 0xb2, 0x87, 0x24, 0x61, 0x51, 0x58, 0x1e, 0xe8,
	0x97, 0x42, 0xc8, 0x93, 0xad, 0xe3, 0x8c, 0x91, 0xbf, 0xc9, 0x0c, 0x50, 0xdb, 0xe6, 0x07, 0xbe,
	0xd7, 0xf9, 0x43, 0xf3, 0x1b, 0x1f, 0x1e, 0x8a, 0x7d, 0xe5, 0x35, 0x0a, 0xf8, 0x44, 0x7e, 0xd3,
	0x54, 0x5d, 0x8d, 0x10, 0x23, 0xc1, 0xf3, 0x66, 0x33, 0x3f, 0x3b, 0x6e, 0x56, 0xf0, 0xed, 0x57,
	0xf2, 0x8b, 0x9f, 0x7a, 0x2b, 0xac, 0xff, 0xff, 0xbe, 0xa7, 0x0f, 0x85, 0x46, 0xf7, 0xe8, 0x5a,
	0x46, 0xa3, 0x7c, 0x85, 0x3b, 0x01, 0x48, 0xbb, 0x32, 0xc9, 0x75, 0xbd, 0x24, 0xf7, 0x8b, 0x8d,
	0x3b, 0xeb, 0x55, 0xdd, 0x3c, 0x39, 0xe2, 0xd7, 0x32, 0x20, 0xd5, 0xfd, 0x28, 0x71, 0x6b, 0xb1,
	0x47, 0x5b, 0x56, 0xd9, 0x91, 0xc2, 0xff, 0x9e, 0xc0, 0xbf, 0x4b, 0xd6, 0x4d, 0xfc, 0x9d, 0x6f,
	0xcc, 0x9e, 0xfe, 0x9a, 0x7c, 0x09, 0xed, 0x23, 0xdf, 0xbf, 0x9a, 0x06, 0x5a, 0x01, 0x6d, 0x1d,
	0x63, 0x86, 0xb0, 0xf2, 0xad, 0xfc, 0x1d, 0x81, 0xbc, 0x4e, 0xd6, 0xb2, 0xc8, 0xe9, 0x9c, 0xf1,
	0x9a, 0xd8, 0xd0, 0x4b, 0xea, 0x7e, 0xa2, 0x88, 0x95, 0xc5, 0x31, 0xe7, 0x80, 0x02, 0x8f, 0x4c,
	0x27, 0x4e, 0x78, 0x44, 0x1a, 0x13, 0x5d, 0x3b, 0x80, 0x6e, 0x7e, 0xe0, 0x23, 0xf7, 0xb4, 0x1f,
	0xcb, 0x87, 0x44, 0xeb, 0xfe, 0x1b, 0xcf, 0xa5, 0xd1, 0xce, 0x66, 0xc5, 0xdf, 0x0f, 0x3e, 0xfa,
	0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xaa, 0x8a, 0x42, 0xd6, 0x71, 0x18, 0x00, 0x00,
}
