package timeout

import (
	"time"

	"github.com/lightningnetwork/lnd/actor"
)

// ID is a unique identifier for a scheduled timeout. This is intentionally
// generic so that it can be used by any component that needs timeout
// scheduling (e.g., peer sessions, sync attempts, retries).
type ID string

// Msg is the sealed interface for messages that can be sent to the timeout
// Actor.
type Msg interface {
	actor.Message

	timeoutMsgSealed()
}

// Resp is the sealed interface for responses from the timeout Actor.
type Resp interface {
	actor.Message

	timeoutRespSealed()
}

// ScheduleTimeoutRequest requests the timeout actor to schedule a timeout.
// When the timeout expires, an ExpiredMsg will be sent to the Callback.
type ScheduleTimeoutRequest struct {
	actor.BaseMessage

	// ID is the unique identifier for this timeout.
	ID ID

	// Duration is how long to wait before the timeout expires.
	Duration time.Duration

	// Callback is the reference the timeout actor sends *ExpiredMsg to
	// when the timeout expires.
	Callback actor.TellOnlyRef[*ExpiredMsg]
}

// MessageType returns the type of this message.
func (m *ScheduleTimeoutRequest) MessageType() string {
	return "ScheduleTimeoutRequest"
}

// timeoutMsgSealed marks this as implementing the sealed Msg interface.
func (m *ScheduleTimeoutRequest) timeoutMsgSealed() {}

// CancelTimeoutRequest requests the timeout actor to cancel a pending timeout.
type CancelTimeoutRequest struct {
	actor.BaseMessage

	// ID is the unique identifier of the timeout to cancel.
	ID ID
}

// MessageType returns the type of this message.
func (m *CancelTimeoutRequest) MessageType() string {
	return "CancelTimeoutRequest"
}

// timeoutMsgSealed marks this as implementing the sealed Msg interface.
func (m *CancelTimeoutRequest) timeoutMsgSealed() {}

// ExpiredMsg is sent back to the callback when a timeout expires. Callers
// usually adapt it into their own message type with MapTimeoutExpired rather
// than receiving it directly.
type ExpiredMsg struct {
	actor.BaseMessage

	// ID is the unique identifier of the timeout that expired.
	ID ID
}

// MessageType returns the type of this message.
func (m *ExpiredMsg) MessageType() string {
	return "ExpiredMsg"
}

// timeoutMsgSealed marks this as implementing the sealed Msg interface.
func (m *ExpiredMsg) timeoutMsgSealed() {}

// ScheduleRecurringTickRequest schedules a recurring tick that fires
// *TickFiredMsg to Callback at every Interval, until cancelled. Cancel
// uses the existing CancelTimeoutRequest keyed by ID. The first fire is
// at Interval (not immediate). Re-scheduling with the same ID stops the
// previous ticker.
type ScheduleRecurringTickRequest struct {
	actor.BaseMessage

	// ID is the unique identifier for this recurring tick. It shares
	// the namespace with one-shot timeout IDs; CancelTimeoutRequest
	// works on either.
	ID ID

	// Interval is the cadence at which TickFiredMsg is delivered.
	Interval time.Duration

	// Callback receives a *TickFiredMsg on each tick.
	Callback actor.TellOnlyRef[*TickFiredMsg]
}

// MessageType returns the type of this message.
func (m *ScheduleRecurringTickRequest) MessageType() string {
	return "ScheduleRecurringTickRequest"
}

// timeoutMsgSealed marks this as implementing the sealed Msg interface.
func (m *ScheduleRecurringTickRequest) timeoutMsgSealed() {}

// TickFiredMsg is delivered to a recurring callback on each tick.
type TickFiredMsg struct {
	actor.BaseMessage

	// ID is the recurring tick that fired.
	ID ID

	// FiredAt is the wall-clock time the tick was generated by the
	// scheduler. Under a fake clock this is the test's logical time.
	FiredAt time.Time
}

// MessageType returns the type of this message.
func (m *TickFiredMsg) MessageType() string {
	return "TickFiredMsg"
}

// timeoutMsgSealed marks this as implementing the sealed Msg interface.
func (m *TickFiredMsg) timeoutMsgSealed() {}

// internalTimerFired is a self-tell delivered by the clock's AfterFunc
// callback when a one-shot timeout fires. It carries the originating
// generation so the handler can drop stale fires that raced with a
// Cancel or reschedule. Internal: never sent by external callers.
type internalTimerFired struct {
	actor.BaseMessage

	// ID identifies the one-shot entry that fired.
	ID ID

	// Gen is the generation stamped at schedule time. A mismatch
	// against the live entry's gen marks this fire as stale.
	Gen uint64
}

// MessageType returns the type of this message.
func (m *internalTimerFired) MessageType() string {
	return "internalTimerFired"
}

// timeoutMsgSealed marks this as implementing the sealed Msg interface.
func (m *internalTimerFired) timeoutMsgSealed() {}

// internalTickFired is a self-tell delivered by the clock's AfterFunc
// callback when a recurring-tick AfterFunc fires. The handler delivers
// TickFiredMsg to the user callback and re-arms the next AfterFunc.
// Internal: never sent by external callers.
type internalTickFired struct {
	actor.BaseMessage

	// ID identifies the recurring entry that fired.
	ID ID

	// Gen is the generation stamped at schedule time.
	Gen uint64

	// FiredAt is the clock time at which AfterFunc invoked the
	// callback. Captured at the timer-goroutine site so each tick
	// timestamp reflects the real fire instant rather than the
	// (potentially later) time at which Receive processes the
	// internalTickFired message.
	FiredAt time.Time
}

// MessageType returns the type of this message.
func (m *internalTickFired) MessageType() string {
	return "internalTickFired"
}

// timeoutMsgSealed marks this as implementing the sealed Msg interface.
func (m *internalTickFired) timeoutMsgSealed() {}

// AckResponse acknowledges a schedule or cancel request.
type AckResponse struct {
	actor.BaseMessage

	// Success indicates whether the operation succeeded.
	Success bool

	// Error contains an error message if Success is false.
	Error string
}

// MessageType returns the type of this message.
func (m *AckResponse) MessageType() string {
	return "AckResponse"
}

// timeoutRespSealed marks this as implementing the sealed Resp interface.
func (m *AckResponse) timeoutRespSealed() {}
