version: "2"
run:
  go: 1.24.6
  build-tags:
    - autopilotrpc
    - chainrpc
    - dev
    - invoicesrpc
    - neutrinorpc
    - peersrpc
    - signrpc
    - walletrpc
    - watchtowerrpc
    - kvdb_etcd
    - kvdb_postgres
    - kvdb_sqlite
    - integration
linters:
  default: all
  disable:
    - bodyclose
    - contextcheck
    - copyloopvar
    - cyclop
    - depguard
    - dogsled
    - err113
    - errname
    - exhaustive
    - exhaustruct
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocyclo
    - godox
    - gosmopolitan
    - inamedparam
    - intrange
    - ireturn
    - lll
    - maintidx
    - nilerr
    - nilnil
    - noctx
    - paralleltest
    - perfsprint
    - prealloc
    - protogetter
    - revive
    - rowserrcheck
    - sqlclosecheck
    - tagalign
    - testifylint
    - testpackage
    - thelper
    - tparallel
    - unparam
    - varnamelen
    - wastedassign
    - wrapcheck
    - wsl
  settings:
    dupl:
      threshold: 200
    errorlint:
      errorf: true
    funlen:
      lines: 200
      statements: 80
    gomoddirectives:
      replace-allow-list:
        - github.com/ulikunitz/xz
        - github.com/gogo/protobuf
        - google.golang.org/protobuf
        - github.com/lightningnetwork/lnd/sqldb
      replace-local: true
    gosec:
      excludes:
        - G402
        - G306
        - G601
        - G115
    nestif:
      min-complexity: 10
    nlreturn:
      block-size: 3
    staticcheck:
      checks:
        - -SA1019
    tagliatelle:
      case:
        rules:
          json: snake
    whitespace:
      multi-if: true
      multi-func: true
    custom:
      ll:
        type: module
        description: Custom lll linter with 'S' log line exclusion.
        settings:
          line-length: 80
          log-regex: ^\s*.*(L|l)og\.(Info|Debug|Trace|Warn|Error|Critical)S\(
          tab-width: 8
    mnd:
      ignored-numbers:
        - '0666'
        - '0755'
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupl
          - funlen
          - gosec
          - revive
        path: _test\.go
      - linters:
          - forcetypeassert
          - revive
        path: mock*
      - linters:
          - funlen
          - gosec
        path: test*
      - linters:
          - dupl
          - forbidigo
          - godot
        path: channeldb/migration*
      - linters:
          - dupl
          - forbidigo
          - godot
        path: channeldb/migtest
      - linters:
          - forbidigo
        path: cmd/commands/*
      - linters:
          - forbidigo
        path: config\.go
      - linters:
          - forbidigo
        path: lnd\.go
      - linters:
          - forcetypeassert
        path: lnmock/*
      - linters:
          - forcetypeassert
        path: mock*
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  new-from-rev: 03eab4db64540aa5f789c617793e4459f4ba9e78
formatters:
  enable:
    - gci
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
skip-files:
    - "mobile\\/.*generated\\.go"
    - "\\.pb\\.go$"
    - "\\.pb\\.gw\\.go$"
    - "internal\\/musig2v040"
skip-dirs:
    - channeldb/migration_01_to_11
    - channeldb/migration/lnwire21

timeout: 10m
