language: go
cache:
  directories:
    - ~/bitcoin/bitcoin-0.17.1/bin
    - ~/protocdl/protoc/bin
    - $GOCACHE
    - $GOPATH/pkg/mod
    - $GOPATH/src/github.com/btcsuite
    - $GOPATH/src/github.com/golang
    - $GOPATH/src/gopkg.in/alecthomas
    - $GOPATH/src/github.com/golang/protobuf
    - $GOPATH/src/google.golang.org/genproto
    - $GOPATH/src/github.com/grpc-ecosystem/grpc-gateway

go:
  - "1.12.x"

env:
  global:
    - GOCACHE=$HOME/.go-build
  matrix:
    - RACE=true
    - ITEST=true
    - COVER=true 

sudo: required

script:
  - GO111MODULE=off bash ./scripts/install_travis_proto.sh
  - bash ./scripts/install_bitcoind.sh
  - export GO111MODULE=on

  # Run unit tests with race condition detector.
  - 'if [ "$RACE" = true ]; then make travis-race ; fi'

  # Run integration tests.
  - 'if [ "$ITEST" = true ]; then make travis-itest; fi'

  # Run unit tests and generate coverage report.
  - 'if [ "$COVER" = true ]; then make travis-cover; fi'

after_script:
  - echo "Uploading to termbin.com..." && find *.log | xargs -I{} sh -c "cat {} | nc termbin.com 9999 | xargs -r0 printf '{} uploaded to %s'"
  - echo "Uploading to file.io..." && tar -zcvO *.log | curl -s -F 'file=@-;filename=logs.tar.gz' https://file.io | xargs -r0 printf 'logs.tar.gz uploaded to %s\n'
