version: '2'
services:

    btc:
      image: btcd
      build:
        context: btcd/
      volumes:
            - shared:/rpc
      environment:
        - RPCUSER="devuser"
        - RPCPASS="devpass"

    btcd:
        extends: btc
        container_name: btcd
        environment:
          - DEBUG="debug"
          - MINING_ADDRESS
        entrypoint: ["./start-btcd.sh"]

    btcctl:
        extends: btc
        container_name: btcctl
        links:
            - "btcd:rpcserver"
        entrypoint: ["./start-btcctl.sh"]

    lnd:
        image: lnd
        build:
          context: ../
          dockerfile: docker/lnd/Dockerfile
        environment:
          - RPCUSER="devuser"
          - RPCPASS="devpass"
          - DEBUG="debug"
        volumes:
            - shared:/rpc
        links:
            - btcd
        entrypoint: ["./start-lnd.sh"]

    walletctl:
        extends: btc
        container_name: walletctl
        environment:
          - RPCUSER="devuser"
          - RPCPASS="devpass"
          - DEBUG="debug"
        volumes:
            - shared:/rpc
        links:
            - "btcwallet:rpcserver"
        entrypoint: [
          "./start-btcctl.sh",
          "--wallet",
        ]

    btcwallet:
        image: btcwallet
        container_name: btcwallet
        build:
          context: btcwallet/
        environment:
          - RPCUSER="devuser"
          - RPCPASS="devpass"
          - DEBUG="debug"
        volumes:
            - shared:/rpc
        links:
            - btcd
        entrypoint: ["./start-btcwallet.sh"]

volumes:
  shared:
    driver: local
