type: google.api.Service
config_version: 3

http:
  rules:
    - selector: devrpc.Dev.ImportGraph
      post: "/v2/dev/importgraph"
      body: "*"
    - selector: devrpc.Dev.Quiesce
      post: "/v2/dev/quiesce"
      body: "*"
